/**
 * Helsinki by area: where prices have gone, and where they might go.
 *
 * The rest of the housing maths takes the home's future value as one typed
 * guess (`homeValueGrowthPct`). This module puts something behind that guess:
 * Statistics Finland's realised sale prices per square metre for every Helsinki
 * postal-code area, 2009 onwards, and the plain arithmetic a careful buyer would
 * do on them - how fast an area has moved, how far it sits below its peak, how
 * much it swings from year to year, and what continuing the trend implies for
 * the year of the purchase.
 *
 * ## What a projection is here, and is not
 *
 * "Continuing the trend" means compounding the last ten years' average yearly
 * change forward. That is arithmetic on the past, not a forecast: nobody knows
 * next year's rates, and the 2022-2025 fall sits inside every ten-year figure
 * this computes. The range around the trend is one standard deviation of the
 * area's own yearly moves, scaled by the square root of the horizon - the
 * random-walk band. Read it as "roughly two years in three, if the future is
 * as unruly as the past", and no more precisely than that.
 *
 * ## The data's limits, which the UI repeats
 *
 * - A €/m² average mixes buildings, floors, conditions and years built; a
 *   renovated flat in a good building is not the average.
 * - Small areas trade a handful of homes a year; Statistics Finland withholds
 *   the cell when there are too few (that is the null in a series), and the
 *   published ones still swing on composition.
 * - Terraced houses are one series per area whatever their size; flats come
 *   in three room-count classes, and "all flats" here is the count-weighted
 *   mean of the three.
 *
 * The data file is generated by `scripts/fetch-helsinki-prices.mjs`; nothing in
 * here knows the numbers, only the shape.
 */

import type { HomeType } from './housing'

/* -------------------------------------------------------------------- types */

/** One figure per year, null where Statistics Finland published none. */
export type Series = (number | null)[]

export type HouseType = 'studio' | 'two' | 'three' | 'terraced'
/** the four published classes, plus the count-weighted mean of the flat classes */
export type SeriesKind = HouseType | 'flats'
/** Statistics Finland's price zones of Helsinki: 1 the centre, 4 the outer suburbs */
export type Zone = 1 | 2 | 3 | 4

export const HOUSE_TYPES: { key: SeriesKind; label: string; short: string }[] = [
  { key: 'studio', label: 'Studios', short: '1 room' },
  { key: 'two', label: 'Two rooms', short: '2 rooms' },
  { key: 'three', label: 'Three rooms or more', short: '3+ rooms' },
  { key: 'flats', label: 'All flats', short: 'all flats' },
  { key: 'terraced', label: 'Terraced houses', short: 'terraced' },
]

export const kindLabel = (kind: SeriesKind): string =>
  HOUSE_TYPES.find((t) => t.key === kind)?.label ?? kind

/** the label a table cell has room for: "2 rooms", "terraced" */
export const kindShort = (kind: SeriesKind): string =>
  HOUSE_TYPES.find((t) => t.key === kind)?.short ?? kind

/**
 * Which published series a home of this kind is measured against. Flats go by
 * room count, the way Statistics Finland splits them; a terraced house is one
 * series whatever its size; a detached house is in none of them - these are
 * the housing-company statistics, and a house on its own plot is sold as real
 * estate, counted elsewhere. A flat that has not said its rooms reads as all
 * flats, the count-weighted mean.
 */
export function seriesKindFor(type: HomeType, rooms: number): SeriesKind | null {
  if (type === 'detached') return null
  if (type === 'terraced') return 'terraced'
  if (rooms <= 0) return 'flats'
  if (rooms < 2) return 'studio'
  if (rooms < 3) return 'two'
  return 'three'
}

/** The zones in plain words - Statistics Finland only numbers them. */
export const ZONE_LABELS: Record<Zone, string> = {
  1: 'city centre',
  2: 'inner districts',
  3: 'middle ring',
  4: 'outer suburbs',
}

export interface AreaRecord {
  /** the postal code, e.g. "00730" */
  code: string
  /** Statistics Finland's area name, e.g. "Tapanila" */
  name: string
  zone: Zone
  /** €/m² per year, aligned with `PriceData.years` */
  price: Record<HouseType, Series>
  /** sales per year, same alignment */
  count: Record<HouseType, Series>
}

export interface CityRecord {
  /** its own, longer year range */
  years: number[]
  price: Record<'all' | 'flats' | 'terraced', Series>
  count: Record<'all' | 'flats' | 'terraced', Series>
}

export type IndexKey = 'helsinki' | 'zone1' | 'zone2' | 'zone3' | 'zone4' | 'capitalRegion' | 'finland'

export interface IndexRecord {
  years: number[]
  /** price indices (2000 = 100), nominal and deflated by consumer prices */
  series: Record<IndexKey, { nominal: Series; real: Series }>
}

export interface LatestQuarter {
  quarter: string
  yearChangePct: number | null
  realYearChangePct: number | null
  pricePerM2: number | null
  count: number | null
  preliminary: boolean
}

export interface PriceData {
  source: string
  tables: string[]
  /** when Statistics Finland last updated the yearly tables */
  updated: string
  fetchedAt: string
  /** where the zone classification comes from */
  zonesFrom: string
  years: number[]
  areas: AreaRecord[]
  city: CityRecord
  index: IndexRecord
  latest: LatestQuarter
}

/* ------------------------------------------------------------------ lookups */

export function findArea(data: PriceData, postalCode: string): AreaRecord | null {
  const code = postalCode.trim()
  if (!code) return null
  return data.areas.find((a) => a.code === code) ?? null
}

export interface Picked {
  values: Series
  counts: Series
}

const FLAT_TYPES = ['studio', 'two', 'three'] as const

/**
 * An area's series for one kind. "All flats" is the count-weighted mean of the
 * three flat classes in each year, using only classes with both a price and a
 * count published - a class with a price but no count cannot be weighted, so
 * it is left out rather than guessed at.
 */
export function areaSeries(area: AreaRecord, kind: SeriesKind): Picked {
  if (kind !== 'flats') return { values: area.price[kind], counts: area.count[kind] }
  const n = area.price.studio.length
  const values: Series = []
  const counts: Series = []
  for (let k = 0; k < n; k++) {
    let sum = 0
    let weight = 0
    for (const t of FLAT_TYPES) {
      const p = area.price[t][k]
      const c = area.count[t][k]
      if (p !== null && c !== null && c > 0) {
        sum += p * c
        weight += c
      }
    }
    values.push(weight > 0 ? sum / weight : null)
    counts.push(weight > 0 ? weight : null)
  }
  return { values, counts }
}

/** Helsinki as a whole, in the class that matches the kind, aligned to the area years. */
export function citySeries(data: PriceData, kind: SeriesKind): Picked {
  const key = kind === 'terraced' ? 'terraced' : 'flats'
  const pick = (s: Series): Series =>
    data.years.map((y) => {
      const k = data.city.years.indexOf(y)
      return k >= 0 ? s[k] : null
    })
  return { values: pick(data.city.price[key]), counts: pick(data.city.count[key]) }
}

/* -------------------------------------------------------------------- maths */

export interface Point {
  year: number
  value: number
}

export interface Growth {
  /** average yearly change, % */
  pct: number
  fromYear: number
  toYear: number
  years: number
}

/** Compound average yearly change, %, from one figure to another over `years`. */
export function cagr(from: number, to: number, years: number): number {
  return (Math.pow(to / from, 1 / years) - 1) * 100
}

/** Compound `value` forward at `pct` per year. */
export function project(value: number, pct: number, years: number): number {
  return value * Math.pow(1 + pct / 100, years)
}

/**
 * The same compounding read as an index instead of a sum: how much higher (or
 * lower) a value stands after `years` at `pct` a year, %. Today is 100, so
 * +36 % means the index has gone 100 → 136 — a projected value stated without
 * committing to a euro figure for the thing being projected.
 */
export function cumulativePct(pct: number, years: number): number {
  return (Math.pow(1 + pct / 100, years) - 1) * 100
}

/**
 * One standard deviation around the trend after `years`, the random-walk way:
 * the drift is the trend, the spread grows with the square root of time, and
 * both live in log space so the band is symmetric in ratios, not in euros.
 */
export function band(
  value: number,
  pct: number,
  volatilityPct: number,
  years: number,
): { low: number; high: number } {
  const drift = years * Math.log(1 + pct / 100)
  const spread = (volatilityPct / 100) * Math.sqrt(years)
  return { low: value * Math.exp(drift - spread), high: value * Math.exp(drift + spread) }
}

const lastPublished = (values: Series): number => {
  for (let k = values.length - 1; k >= 0; k--) if (values[k] !== null) return k
  return -1
}

/**
 * Average yearly change over the last `span` years, or null when there is not
 * enough of a window. A gap at the start of the window shortens it rather than
 * reaching further back than asked; under `minYears` the figure would carry a
 * name it does not deserve, so none is given.
 */
export function growthOver(
  years: number[],
  values: Series,
  span: number,
  minYears: number = Math.ceil(span / 2),
): Growth | null {
  const last = lastPublished(values)
  if (last < 0) return null
  const toYear = years[last]
  const target = toYear - span
  let from = -1
  for (let k = 0; k < last; k++) {
    if (years[k] >= target && values[k] !== null) {
      from = k
      break
    }
  }
  if (from < 0) return null
  const n = toYear - years[from]
  if (n < minYears || n <= 0) return null
  return { pct: cagr(values[from]!, values[last]!, n), fromYear: years[from], toYear, years: n }
}

/** Average yearly change from one particular year to the latest figure. */
export function growthSince(years: number[], values: Series, fromYear: number): Growth | null {
  const last = lastPublished(values)
  const from = years.indexOf(fromYear)
  if (last < 0 || from < 0 || from >= last || values[from] === null) return null
  const n = years[last] - fromYear
  return { pct: cagr(values[from], values[last]!, n), fromYear, toYear: years[last], years: n }
}

export interface SeriesSummary {
  latest: Point | null
  first: Point | null
  /** years with a published figure */
  points: number
  peak: Point | null
  /** the latest figure against the peak, % - zero when the latest is the peak */
  fromPeakPct: number | null
  /**
   * Standard deviation of the yearly log changes between consecutive published
   * years, % - null under four changes, where a deviation says nothing.
   */
  volatilityPct: number | null
  growth5: Growth | null
  growth10: Growth | null
  growthAll: Growth | null
}

function sampleStdev(xs: number[]): number {
  const mean = xs.reduce((a, b) => a + b, 0) / xs.length
  const sq = xs.reduce((a, x) => a + (x - mean) * (x - mean), 0)
  return Math.sqrt(sq / (xs.length - 1))
}

export function describeSeries(years: number[], values: Series): SeriesSummary {
  const idx: number[] = []
  values.forEach((v, k) => {
    if (v !== null) idx.push(k)
  })
  if (idx.length === 0) {
    return {
      latest: null,
      first: null,
      points: 0,
      peak: null,
      fromPeakPct: null,
      volatilityPct: null,
      growth5: null,
      growth10: null,
      growthAll: null,
    }
  }
  const at = (k: number): Point => ({ year: years[k], value: values[k]! })
  const last = idx[idx.length - 1]
  let peakK = idx[0]
  for (const k of idx) if (values[k]! > values[peakK]!) peakK = k

  const changes: number[] = []
  for (let i = 1; i < idx.length; i++) {
    const a = idx[i - 1]
    const b = idx[i]
    if (years[b] - years[a] === 1) changes.push(Math.log(values[b]! / values[a]!))
  }

  return {
    latest: at(last),
    first: at(idx[0]),
    points: idx.length,
    peak: at(peakK),
    fromPeakPct: (values[last]! / values[peakK]! - 1) * 100,
    volatilityPct: changes.length >= 4 ? sampleStdev(changes) * 100 : null,
    growth5: growthOver(years, values, 5),
    growth10: growthOver(years, values, 10),
    growthAll: growthOver(years, values, years[last] - years[0], 2),
  }
}

/* ------------------------------------------------------------------ outlook */

export interface Subject {
  code: string
  name: string
  /** null for Helsinki as a whole */
  zone: Zone | null
}

/**
 * The horizons every projection is stated at: the purchase year, and ten and
 * twenty years after it - the life of the loan, roughly. "Where to buy" is a
 * question about the second and third; the first is what the purchase costs.
 */
export const HORIZON_OFFSETS = [0, 10, 20] as const

export interface Horizon {
  year: number
  /** years from the latest published figure */
  years: number
  atTrend: { value: number; low: number | null; high: number | null } | null
  atGuess: number
  /** at the long-run rate of the area's price zone - null when none was given */
  atLongRun: number | null
}

export interface Projection {
  /** the purchase year - the first horizon's year (when there are horizons) */
  targetYear: number
  /** the window whose average change is continued - ten years when there are ten */
  trend: Growth | null
  /**
   * The series stopped more than two years before the data does - too few
   * sales since for a figure. Its trend is still reported, but nothing is
   * continued (`horizons` is empty): eight years of compounding from a stale
   * number is a headline, not an estimate.
   */
  stale: boolean
  /** the deviation the band uses: the area's own, or the city's where the area has too few years */
  volatilityUsedPct: number | null
  guessPct: number
  /**
   * The steadier yardstick for the far horizons: the average yearly change of
   * the price index for the area's whole zone over everything it covers
   * (1988 on), % - a ten-year window in one postal code is a thin base to
   * compound twenty years from.
   */
  longRunPct: number | null
  horizons: Horizon[]
}

export interface AreaOutlook extends Subject {
  years: number[]
  values: Series
  counts: Series
  summary: SeriesSummary
  /** sales in the latest published year, when published */
  latestCount: number | null
  /**
   * The area against Helsinki as a whole in the same year, % above (+) or
   * below (-), now and ten years earlier - whether the gap has widened.
   */
  vsCity: { nowPct: number; thenPct: number | null; thenYear: number | null } | null
  projection: Projection | null
}

/**
 * Everything the card says about one area (or the city) for one kind of home:
 * the summary of its history, its standing against the city, and where
 * continuing the trend - and the reader's own guess - would put it by the
 * target year.
 */
export function outlook(
  subject: Subject,
  years: number[],
  picked: Picked,
  cityValues: Series,
  cityVolatilityPct: number | null,
  targetYear: number,
  guessPct: number,
  longRunPct: number | null = null,
): AreaOutlook {
  const { values, counts } = picked
  const summary = describeSeries(years, values)
  const latest = summary.latest

  let vsCity: AreaOutlook['vsCity'] = null
  let projection: Projection | null = null
  let latestCount: number | null = null

  if (latest) {
    const k = years.indexOf(latest.year)
    latestCount = counts[k] ?? null

    const cityNow = cityValues[k]
    if (cityNow) {
      const thenK = years.indexOf(latest.year - 10)
      const thenValue = thenK >= 0 ? values[thenK] : null
      const cityThen = thenK >= 0 ? cityValues[thenK] : null
      const then = thenValue && cityThen ? (thenValue / cityThen - 1) * 100 : null
      vsCity = {
        nowPct: (latest.value / cityNow - 1) * 100,
        thenPct: then,
        thenYear: then === null ? null : latest.year - 10,
      }
    }

    const n0 = Math.max(1, targetYear - latest.year)
    const trend = summary.growth10 ?? summary.growthAll
    const stale = years[years.length - 1] - latest.year > 2
    const vol = summary.volatilityPct ?? cityVolatilityPct
    const trendPct = trend !== null && !stale ? trend.pct : null
    // A stale series is not continued at all - not at its trend, not at the
    // reader's guess, not at the zone's rate: every one of them would start
    // from a figure the market left behind years ago.
    const offsets: readonly number[] = stale ? [] : HORIZON_OFFSETS
    const horizons: Horizon[] = offsets.map((offset) => {
      const n = n0 + offset
      let atTrend: Horizon['atTrend'] = null
      if (trendPct !== null) {
        const value = project(latest.value, trendPct, n)
        const range = vol === null ? { low: null, high: null } : band(latest.value, trendPct, vol, n)
        atTrend = { value, ...range }
      }
      return {
        year: latest.year + n,
        years: n,
        atTrend,
        atGuess: project(latest.value, guessPct, n),
        atLongRun: longRunPct === null ? null : project(latest.value, longRunPct, n),
      }
    })
    projection = {
      targetYear: latest.year + n0,
      trend,
      stale,
      volatilityUsedPct: trendPct !== null ? vol : null,
      guessPct,
      longRunPct,
      horizons,
    }
  }

  return {
    code: subject.code,
    name: subject.name,
    zone: subject.zone,
    years,
    values,
    counts,
    summary,
    latestCount,
    vsCity,
    projection,
  }
}

/* -------------------------------------------------------------- the long run */

export interface IndexStats {
  sinceStart: Growth | null
  since2015: Growth | null
  peak: Point | null
  fromPeakPct: number | null
  /** the deepest fall from a peak to a later trough anywhere in the series */
  worst: { fromYear: number; toYear: number; pct: number } | null
  /** years that ended below the year before */
  downYears: number
}

/** What a long price index says about the range of outcomes an area has produced. */
export function indexStats(years: number[], values: Series): IndexStats {
  const s = describeSeries(years, values)
  let worst: IndexStats['worst'] = null
  let downYears = 0
  let peak: Point | null = null
  let prev: number | null = null
  for (let k = 0; k < values.length; k++) {
    const v = values[k]
    if (v === null) continue
    if (prev !== null && v < prev) downYears++
    prev = v
    if (!peak || v > peak.value) peak = { year: years[k], value: v }
    const dd = (v / peak.value - 1) * 100
    if (!worst || dd < worst.pct) worst = { fromYear: peak.year, toYear: years[k], pct: dd }
  }
  return {
    sinceStart: s.first && s.latest ? growthSince(years, values, s.first.year) : null,
    since2015: growthSince(years, values, 2015),
    peak: s.peak,
    fromPeakPct: s.fromPeakPct,
    worst: worst !== null && worst.pct < 0 ? worst : null,
    downYears,
  }
}

/* ------------------------------------------------- one place, nominally */

/**
 * The two nominal rates that bear on one address, with no view of its price.
 *
 * The "Helsinki by area" card asks the reader to pick a type of home and a
 * horizon before it says anything; a side-by-side table of candidates cannot
 * ask that of every column, so this fixes both choices in a way it can then
 * state plainly:
 *
 * - **the zone's long run** — the average yearly change of Statistics
 *   Finland's *nominal* price index for the area's whole price zone, over
 *   everything the index covers (1988 on). It needs no type of home at all,
 *   which is exactly why it is the figure a table of mixed candidates can
 *   carry.
 * - **the area's own trend** — the last ten years of realised €/m² in that one
 *   postal code, for the kind of home the place says it is: a flat by its room
 *   count, a terraced house as its own series, and all flats (the
 *   count-weighted mean of the three room-count classes) for a flat that has
 *   not said. The kind matters more than it looks: Itä-Pakila publishes almost
 *   no flat prices and seventeen unbroken years of terraced ones, so the same
 *   address reads "stops at 2019" as a flat and "+1,1 %/yr" as a terraced house.
 *   A detached house (`kind` null) has no series at all - the statistics cover
 *   housing companies - and says so rather than borrowing one.
 *
 * A series that stopped more than two years before the data does yields no
 * trend — same rule as `outlook`, and for the same reason: compounding from a
 * figure the market left behind is a headline, not an estimate. The zone's
 * long run survives that, since the index does not depend on the area trading.
 */
export interface NominalRates {
  /** the area the postal code resolves to, or null when the data has no such code */
  area: AreaRecord | null
  /** the series the trend was read from; null for a kind the data does not cover */
  kind: SeriesKind | null
  /** average yearly change of the zone's nominal price index, %/yr */
  longRunPct: number | null
  /** the first year the index covers */
  longRunSince: number
  /** the area's own all-flats trend, %/yr — null when there is none to continue */
  trendPct: number | null
  /** the window that trend spans, years */
  trendYears: number | null
  /** the last year the area published a figure, whether or not it is recent */
  latestYear: number | null
  /** the series stopped long enough ago that nothing is continued from it */
  stale: boolean
}

export function nominalRates(
  data: PriceData,
  postalCode: string,
  kind: SeriesKind | null = 'flats',
): NominalRates {
  const area = findArea(data, postalCode)
  const idx = data.index
  const longRunSince = idx.years[0]
  const none = {
    longRunPct: null,
    longRunSince,
    trendPct: null,
    trendYears: null,
    latestYear: null,
    stale: false,
  }
  if (!area) return { area: null, kind, ...none }
  const key = `zone${area.zone}` as IndexKey
  const longRunPct = indexStats(idx.years, idx.series[key].nominal).sinceStart?.pct ?? null
  // The zone's index stands whatever the home is; only the area trend needs a series.
  if (kind === null) return { area, kind, ...none, longRunPct }
  const summary = describeSeries(data.years, areaSeries(area, kind).values)
  const latest = summary.latest
  const stale = latest !== null && data.years[data.years.length - 1] - latest.year > 2
  const trend = summary.growth10 ?? summary.growthAll
  return {
    area,
    kind,
    longRunPct,
    longRunSince,
    trendPct: trend && !stale ? trend.pct : null,
    trendYears: trend && !stale ? trend.years : null,
    latestYear: latest?.year ?? null,
    stale,
  }
}

/* ---------------------------------------------------------- reading a trend */

/** Average yearly change between two particular years, both of which must be published. */
export function growthBetween(
  years: number[],
  values: Series,
  fromYear: number,
  toYear: number,
): Growth | null {
  const a = years.indexOf(fromYear)
  const b = years.indexOf(toYear)
  if (a < 0 || b < 0 || b <= a) return null
  const va = values[a]
  const vb = values[b]
  if (va === null || vb === null || va <= 0) return null
  return { pct: cagr(va, vb, toYear - fromYear), fromYear, toYear, years: toYear - fromYear }
}

export interface Divergence {
  year: number
  /** the area's change on the year before, % */
  areaPct: number
  /** the city's change over the same year, % */
  cityPct: number
  /** whether the year pushed the same way as the whole gap to the city - only those can explain it */
  aligned: boolean
}

/**
 * Why an area's trend reads the way it does - the checks a careful reader
 * would run before believing a figure that disagrees with the zone's long run.
 */
export interface TrendRead {
  /** the window the trend is read from */
  trend: Growth
  /**
   * The same figure with the window moved one year at either end. A wide
   * spread means the trend is mostly the choice of a start year.
   */
  windows: { low: number; high: number; fragile: boolean }
  /** sales a year inside the window; thin when a handful of homes decide each year's figure */
  sample: { median: number; min: number; thin: boolean } | null
  /** Helsinki, same class of home, over the same years */
  city: Growth | null
  /** area minus city, percentage points a year */
  excessPct: number | null
  /**
   * The years in which the area moved hardest against the city, largest
   * first - at most two, and only moves of eight points or more. A gap to the
   * city that arrives in one or two such years, while the rest of the time the
   * area keeps the city's pace, is the signature of a change in what sold, not
   * of the same homes gaining value.
   */
  divergences: Divergence[]
  /**
   * How much of the whole gap to the city the divergent years that push the
   * gap's way account for, 0-1. Null when there is no gap, or when every
   * divergent year cut against it.
   */
  divergenceShare: number | null
  /** the area and the city against their own peaks over the whole series */
  fromPeak: {
    area: number | null
    areaPeakYear: number | null
    city: number | null
    cityPeakYear: number | null
  }
  /** the zone's price index over the same years */
  zone: Growth | null
  /** area minus zone, percentage points a year */
  zoneExcessPct: number | null
}

/** How wide a spread between neighbouring windows marks a trend as fragile, points a year. */
const FRAGILE_SPREAD_PP = 1.5
/** Under this many sales a year, the yearly figures wobble more than the homes do. */
const THIN_SAMPLE = 20
/** A year counts as moving against the city from this many points of difference. */
const DIVERGENCE_PP = 8

export function readTrend(
  years: number[],
  values: Series,
  counts: Series,
  cityValues: Series,
  zoneIndex: { years: number[]; values: Series } | null,
): TrendRead | null {
  const s = describeSeries(years, values)
  const trend = s.growth10 ?? s.growthAll
  if (!trend) return null
  const { fromYear, toYear } = trend
  const ai = years.indexOf(fromYear)
  const bi = years.indexOf(toYear)

  // The window moved a year at either end - only windows still two years long count.
  const alternatives = [
    growthBetween(years, values, fromYear - 1, toYear),
    growthBetween(years, values, fromYear + 1, toYear),
    growthBetween(years, values, fromYear, toYear - 1),
  ].filter((g): g is Growth => g !== null && g.years >= 2)
  const pcts = [trend.pct, ...alternatives.map((g) => g.pct)]
  const low = Math.min(...pcts)
  const high = Math.max(...pcts)
  const windows = { low, high, fragile: high - low > FRAGILE_SPREAD_PP }

  const inWindow: number[] = []
  for (let k = ai; k <= bi; k++) {
    const c = counts[k]
    if (c !== null) inWindow.push(c)
  }
  let sample: TrendRead['sample'] = null
  if (inWindow.length) {
    const sorted = [...inWindow].sort((a, b) => a - b)
    const median = sorted[Math.floor(sorted.length / 2)]
    sample = { median, min: sorted[0], thin: median < THIN_SAMPLE }
  }

  const city = growthBetween(years, cityValues, fromYear, toYear)
  const excessPct = city ? trend.pct - city.pct : null

  const divergences: Divergence[] = []
  let divergenceShare: number | null = null
  if (city) {
    const totalLogExcess =
      Math.log(values[bi]! / values[ai]!) - Math.log(cityValues[bi]! / cityValues[ai]!)
    const moves: { year: number; areaPct: number; cityPct: number; logDiff: number }[] = []
    for (let k = ai + 1; k <= bi; k++) {
      const a0 = values[k - 1]
      const a1 = values[k]
      const c0 = cityValues[k - 1]
      const c1 = cityValues[k]
      if (a0 === null || a1 === null || c0 === null || c1 === null) continue
      moves.push({
        year: years[k],
        areaPct: (a1 / a0 - 1) * 100,
        cityPct: (c1 / c0 - 1) * 100,
        logDiff: Math.log(a1 / a0) - Math.log(c1 / c0),
      })
    }
    moves.sort((x, y) => Math.abs(y.logDiff) - Math.abs(x.logDiff))
    const top = moves.filter((m) => Math.abs(m.areaPct - m.cityPct) >= DIVERGENCE_PP).slice(0, 2)
    // Only the years that push the same way as the gap can explain it; a year
    // that cut the other way is listed, but it is not part of the answer.
    const hasGap = Math.abs(totalLogExcess) > 1e-9
    for (const m of top) {
      divergences.push({
        year: m.year,
        areaPct: m.areaPct,
        cityPct: m.cityPct,
        aligned: hasGap && Math.sign(m.logDiff) === Math.sign(totalLogExcess),
      })
    }
    const aligned = top.filter((_, i) => divergences[i].aligned)
    if (aligned.length) {
      const share = aligned.reduce((sum, m) => sum + m.logDiff, 0) / totalLogExcess
      divergenceShare = Math.min(1, share)
    }
  }

  const cityS = describeSeries(years, cityValues)
  const zone = zoneIndex ? growthBetween(zoneIndex.years, zoneIndex.values, fromYear, toYear) : null

  return {
    trend,
    windows,
    sample,
    city,
    excessPct,
    divergences,
    divergenceShare,
    fromPeak: {
      area: s.fromPeakPct,
      areaPeakYear: s.peak?.year ?? null,
      city: cityS.fromPeakPct,
      cityPeakYear: cityS.peak?.year ?? null,
    },
    zone,
    zoneExcessPct: zone ? trend.pct - zone.pct : null,
  }
}

/* ------------------------------------------------------------------ the year */

/**
 * The year the projection runs to. Zero (the default) means "two years from
 * now" - the horizon of somebody saving up - and never earlier than the year
 * after the last published figure, since a projection into the past is a
 * contradiction.
 */
export function resolveProjectionYear(setting: number, latestYear: number, now = new Date()): number {
  const floor = latestYear + 1
  if (setting >= floor) return Math.round(setting)
  return Math.max(floor, now.getFullYear() + 2)
}
