// Generated by scripts/fetch-helsinki-prices.mjs on 2026-09-14 - do not edit by hand.
// Source: Tilastokeskus (Statistics Finland), osakeasuntojen hinnat; tables 13mu, 13mx, 13mz, 15is; yearly tables updated 2026-05-19.
// Zones: Tilastokeskus, aluejako neljännesvuositilastossa (ashi_2018-05-02_luo_001).
import type { PriceData } from '../areas'

export const HELSINKI_PRICES: PriceData = {
  "source": "Tilastokeskus (Statistics Finland), osakeasuntojen hinnat",
  "tables": ["13mu","13mx","13mz","15is"],
  "updated": "2026-05-19",
  "fetchedAt": "2026-09-14",
  "zonesFrom": "Tilastokeskus, aluejako neljännesvuositilastossa (ashi_2018-05-02_luo_001)",
  "years": [2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025],
  "areas": [
    {
      "code": "00100",
      "name": "Helsinki keskusta - Etu-Töölö",
      "zone": 1,
      "price": {
        "studio": [4817,5386,5649,6087,6311,6530,6495,5780,7288,7867,8136,8419,9002,8797,8018,7812,7371],
        "two": [4470,5104,5744,5898,6092,6003,6313,6138,6772,7098,7259,7773,8094,8357,7682,7263,7254],
        "three": [4234,5198,5549,5663,5542,5719,5631,5957,6403,6540,6946,7153,8090,8054,7594,7240,7353],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [116,131,138,117,111,108,101,167,100,112,120,110,160,141,96,90,136],
        "two": [167,186,211,183,141,141,181,157,167,150,156,178,259,194,132,128,152],
        "three": [122,149,154,118,140,107,141,149,163,133,161,195,250,140,101,117,132],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00120",
      "name": "Punavuori - Bulevardi",
      "zone": 1,
      "price": {
        "studio": [5040,5525,5944,6097,6453,6207,6755,6768,7805,7677,8216,8702,9460,8673,8028,8614,7851],
        "two": [5044,5420,5490,5876,6256,5929,6372,6428,6867,7454,7538,7993,8683,8665,7613,7919,8066],
        "three": [5122,6037,5588,5907,6299,5891,6400,6588,7025,7467,7832,8065,8908,8215,8018,7873,8886],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [51,68,40,63,54,40,42,47,50,60,51,55,70,58,40,36,41],
        "two": [70,83,65,72,72,48,77,76,77,50,84,82,105,58,65,53,67],
        "three": [60,66,53,68,73,63,78,53,79,85,75,75,103,60,46,75,90],
        "terraced": [null,null,null,null,null,null,null,null,null,1,null,1,1,1,null,null,1]
      }
    },
    {
      "code": "00130",
      "name": "Kaartinkaupunki",
      "zone": 1,
      "price": {
        "studio": [5436,5610,6399,6214,7088,null,6423,7642,8534,8249,8802,null,9303,9400,8648,8604,7877],
        "two": [5333,5870,6316,6327,6577,6794,null,7474,7487,7960,8084,8588,9480,10691,7744,null,7546],
        "three": [5209,5234,null,6219,null,7116,6217,7616,7129,7561,8079,8083,10024,8785,9153,8128,7684],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [11,11,8,12,8,4,8,13,7,7,13,5,14,10,14,10,19],
        "two": [11,11,8,9,11,12,5,6,16,6,14,11,22,13,10,5,14],
        "three": [14,16,7,17,11,17,18,20,13,14,20,19,21,16,16,10,19],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00140",
      "name": "Kaivopuisto - Ullanlinna",
      "zone": 1,
      "price": {
        "studio": [5390,5837,6281,6884,6962,6856,6966,7344,7722,8505,8581,8948,9470,9623,8144,8031,8002],
        "two": [5060,5563,6245,6120,6597,6418,6700,6930,7415,7704,8425,8416,9311,9147,8347,7928,8129],
        "three": [5421,6400,7037,6882,6731,7020,7005,7459,7438,8339,8879,8811,9945,10041,9829,8944,9653],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [98,89,83,70,68,62,75,62,79,53,76,73,66,55,63,58,80],
        "two": [88,77,87,87,75,56,86,98,85,76,77,69,102,54,67,56,72],
        "three": [57,77,67,68,76,57,76,69,79,72,93,92,84,74,63,61,65],
        "terraced": [1,null,null,null,null,null,null,null,1,1,null,null,1,null,null,null,null]
      }
    },
    {
      "code": "00150",
      "name": "Punavuori - Eira - Hernesaari",
      "zone": 1,
      "price": {
        "studio": [4906,5352,5786,6071,6362,6862,6915,7093,7398,7896,8307,8739,9175,8767,8218,7850,7796],
        "two": [4811,5220,5807,5951,6125,6348,6285,6464,6909,7571,7872,8243,8715,8683,7744,7893,8047],
        "three": [5422,6230,6319,6147,7166,6317,6751,6773,7857,7610,8286,8540,10318,9585,8889,9275,8852],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [174,193,137,182,116,122,144,118,128,139,123,134,144,121,79,100,91],
        "two": [118,134,113,157,111,76,127,121,104,107,133,129,120,96,77,85,97],
        "three": [61,81,66,96,64,63,81,60,77,70,97,71,79,85,46,67,78],
        "terraced": [2,null,null,3,null,null,1,2,1,1,2,1,null,null,1,5,3]
      }
    },
    {
      "code": "00160",
      "name": "Katajanokka",
      "zone": 1,
      "price": {
        "studio": [4838,5181,5465,6487,6363,6590,6420,6746,6659,7199,7396,8236,8723,8156,7788,8065,7497],
        "two": [4943,5615,5406,5888,6272,5943,5951,5954,6207,6438,6535,7386,8112,7435,8852,6265,7425],
        "three": [5184,5251,6567,6552,6041,5611,5945,6105,5980,6371,6649,7324,8143,7958,7711,7427,7288],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [14,8,14,15,12,8,13,15,20,20,14,18,29,20,14,21,25],
        "two": [24,33,23,34,31,20,39,35,23,36,31,36,52,36,30,23,53],
        "three": [44,31,20,27,31,23,43,42,44,37,57,53,62,36,27,30,44],
        "terraced": [null,null,null,null,2,1,null,1,2,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00170",
      "name": "Kruununhaka",
      "zone": 1,
      "price": {
        "studio": [4891,5679,5808,6270,6444,6696,6824,7406,7664,7496,7838,8680,8481,8717,8221,7927,7344],
        "two": [4575,5265,5773,5761,6179,5972,6229,6276,6838,7186,7365,7770,7965,8382,7570,7321,7399],
        "three": [4823,5417,5601,5797,6142,5858,6185,6025,6444,6481,6964,7274,7951,8071,7285,7297,7149],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [68,60,55,47,62,47,72,65,48,48,54,63,57,53,31,36,41],
        "two": [71,78,54,74,60,52,48,77,63,63,62,72,71,53,48,46,52],
        "three": [65,58,59,71,54,56,59,66,65,84,72,85,98,78,64,41,69],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00180",
      "name": "Kamppi - Ruoholahti",
      "zone": 1,
      "price": {
        "studio": [4879,5323,5771,5825,6293,6649,6644,7360,7712,8017,7983,8719,9064,8574,7639,7376,7157],
        "two": [4564,5055,5407,5585,5710,5901,6122,6299,6694,7053,6987,7863,7877,7940,7120,6870,6493],
        "three": [4436,4730,4958,5156,5283,5336,5976,6296,6427,6876,6893,7564,7759,8114,7546,6431,6655],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [103,116,103,105,75,94,110,90,83,81,83,102,123,89,88,65,98],
        "two": [107,97,93,101,81,89,173,92,90,94,126,129,126,108,74,77,154],
        "three": [60,71,55,87,63,62,98,81,85,67,102,112,124,112,73,82,100],
        "terraced": [4,2,null,2,4,3,null,3,2,2,1,3,3,4,2,2,2]
      }
    },
    {
      "code": "00190",
      "name": "Suomenlinna",
      "zone": 4,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,1,null,null,null,1,null,1,null,null,null],
        "three": [null,null,null,1,1,null,null,2,2,null,1,null,null,2,1,null,null],
        "terraced": [null,null,null,null,null,null,null,null,2,null,null,1,1,null,1,null,null]
      }
    },
    {
      "code": "00200",
      "name": "Pohjois-Lauttasaari",
      "zone": 2,
      "price": {
        "studio": [4082,4611,4874,5173,5345,5554,5572,5897,6425,6680,7019,7278,7809,7656,6632,6467,6449],
        "two": [3616,4091,4405,4574,4826,4853,4945,5079,5423,5779,5966,6531,6901,7118,6392,6115,6017],
        "three": [3724,4182,4574,4596,4676,4773,4762,4963,5147,5640,5677,6426,6973,7167,6699,6276,6444],
        "terraced": [5341,4701,5535,5281,5440,6180,5957,null,6195,6195,6277,7089,8377,8096,7503,7119,7948]
      },
      "count": {
        "studio": [114,112,103,107,92,74,96,84,98,72,85,86,95,68,67,68,83],
        "two": [200,218,201,218,158,166,166,175,218,163,196,194,206,165,146,154,169],
        "three": [153,164,122,188,132,144,138,144,159,144,163,197,189,153,132,162,178],
        "terraced": [8,12,10,10,18,12,14,11,15,12,20,10,20,10,11,18,14]
      }
    },
    {
      "code": "00210",
      "name": "Vattuniemi",
      "zone": 2,
      "price": {
        "studio": [4260,4688,4891,4839,5576,5400,5574,6454,6104,6325,6691,6975,7457,7915,6517,6616,5981],
        "two": [4193,4497,4639,4860,4986,5123,5324,5378,5369,5951,6027,6430,6918,7120,6389,6253,5918],
        "three": [4464,4665,4871,4936,5125,5204,5197,5439,5622,5935,6312,6882,7087,7078,6738,6729,6664],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [17,23,17,42,22,22,30,18,19,14,17,23,39,45,31,23,51],
        "two": [50,60,63,87,70,71,89,89,96,85,116,100,105,108,62,62,104],
        "three": [67,70,79,88,75,77,103,105,141,103,132,150,110,122,97,88,120],
        "terraced": [2,1,null,1,null,2,2,4,2,5,4,3,3,null,null,1,2]
      }
    },
    {
      "code": "00220",
      "name": "Jätkäsaari",
      "zone": 1,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,9167,null,8146,7090],
        "two": [null,null,null,null,null,null,null,null,null,null,null,7604,8179,8559,7308,7748,7549],
        "three": [null,null,null,null,null,null,null,null,null,null,null,7301,8198,7781,8058,6651,7077],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,1,1,1,2,7,7,8,10,11,20],
        "two": [null,null,null,null,null,null,null,null,5,5,13,18,21,26,56,21,36],
        "three": [null,null,null,null,null,null,2,10,6,7,21,38,53,52,79,67,74],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00240",
      "name": "Länsi-Pasila",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,null,5426,null,null,null,5679,5640,6242,6575,5847,null,5969,5011],
        "two": [2860,3151,3185,3849,4209,4468,4301,4626,4647,4898,4937,5543,5372,5220,4808,4668,4514],
        "three": [2822,3240,3452,3493,4045,4425,4269,4371,4676,4781,4908,5361,5616,5328,4979,5010,4051],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [3,2,3,4,6,7,2,4,4,7,7,6,18,34,4,35,32],
        "two": [19,23,15,13,15,27,33,23,18,34,37,33,46,55,27,50,38],
        "three": [16,19,12,16,13,17,34,37,39,30,31,43,35,47,35,33,56],
        "terraced": [null,null,null,1,null,null,null,null,2,1,null,null,null,null,null,null,1]
      }
    },
    {
      "code": "00250",
      "name": "Taka-Töölö",
      "zone": 2,
      "price": {
        "studio": [4562,4923,5145,5606,6043,5878,6105,6382,6721,7048,7345,7398,7959,7572,7368,6899,6758],
        "two": [4257,4608,4904,5061,5288,5291,5499,5721,5990,6257,6590,6839,7117,7021,6531,6687,6207],
        "three": [3968,4445,4659,4914,4956,5022,5104,5247,5601,5960,6118,6357,7021,6962,6600,6336,6250],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [108,121,94,113,102,108,120,93,82,108,101,97,104,105,84,85,105],
        "two": [158,178,146,184,140,168,153,125,149,140,167,162,192,156,117,121,120],
        "three": [66,79,96,93,75,76,104,63,101,86,104,108,110,82,62,67,76],
        "terraced": [null,null,null,null,null,null,null,2,1,2,null,1,null,1,1,null,1]
      }
    },
    {
      "code": "00260",
      "name": "Keski-Töölö",
      "zone": 1,
      "price": {
        "studio": [4800,4924,5665,5773,6096,6445,6350,6396,7122,7010,7625,8420,8331,8570,7269,7091,6638],
        "two": [4401,4945,5270,5405,5484,5774,5601,5929,6232,6854,6620,7167,7990,7572,7546,7426,7062],
        "three": [4358,4972,5274,5228,5942,5684,5888,5613,5967,6366,6674,7048,7497,7898,7138,7780,7486],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [45,40,46,26,33,28,38,28,28,27,29,31,45,51,22,26,41],
        "two": [49,27,55,76,49,39,43,50,42,35,69,61,61,71,38,43,79],
        "three": [54,52,63,63,36,47,45,46,42,72,51,43,57,66,40,44,45],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00270",
      "name": "Pohjois-Meilahti",
      "zone": 2,
      "price": {
        "studio": [4707,4891,5215,5586,5949,5946,6105,6517,6866,6883,7115,7598,8030,7535,7001,6386,5811],
        "two": [3951,4410,4603,4899,5176,5254,5145,5546,5872,6110,6383,6585,6800,6673,6046,5429,5546],
        "three": [3747,4275,4366,4608,4900,4953,4821,4898,5279,5469,5962,6184,6286,6752,5905,5559,5653],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [76,68,50,62,50,48,52,46,45,40,46,45,35,43,31,30,41],
        "two": [101,121,99,107,67,84,101,93,79,87,90,84,105,86,66,58,64],
        "three": [55,60,67,78,52,54,56,61,59,64,57,72,71,60,42,44,39],
        "terraced": [null,1,null,null,null,1,1,3,null,1,null,1,2,2,null,null,null]
      }
    },
    {
      "code": "00280",
      "name": "Ruskeasuo",
      "zone": 2,
      "price": {
        "studio": [4015,4480,4624,4923,5239,4979,5644,5635,5750,6087,6304,6547,6796,6542,6346,null,5490],
        "two": [3807,4262,4438,4664,4777,5105,4954,5118,5262,5703,5741,6397,6692,6702,5544,5480,5299],
        "three": [3562,4045,4354,4391,4815,4540,4860,5013,5072,5120,5303,5937,6255,6321,5481,5582,4864],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [14,12,15,10,10,17,7,12,17,9,13,16,9,16,7,5,10],
        "two": [23,24,37,42,28,31,26,41,31,31,32,29,38,18,24,21,32],
        "three": [20,29,21,23,32,20,15,25,25,29,20,18,28,23,18,20,15],
        "terraced": [null,null,1,null,2,null,null,null,null,null,1,null,null,null,null,null,null]
      }
    },
    {
      "code": "00290",
      "name": "Meilahden sairaala-alue",
      "zone": 2,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,1,null,1,1,1,null,null,null,null,null,null,null,1,1,null],
        "three": [null,1,null,1,1,1,null,null,null,null,1,null,null,null,2,null,1],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00300",
      "name": "Pikku Huopalahti",
      "zone": 2,
      "price": {
        "studio": [null,null,4426,null,null,null,null,4643,4776,null,null,null,null,null,5258,5321,4745],
        "two": [null,4717,4177,4143,4652,4501,5765,5464,5982,6544,6049,5791,5631,5731,4951,4650,4490],
        "three": [3527,4243,4620,4744,null,null,5339,5070,null,4791,5563,5902,5354,5478,4126,4633,4468],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [7,5,10,4,5,4,6,10,6,5,6,7,6,5,8,7,31],
        "two": [22,34,38,23,28,19,23,25,34,24,21,28,36,32,18,19,38],
        "three": [30,29,30,30,25,18,26,31,21,22,30,36,19,26,14,15,33],
        "terraced": [null,1,3,2,1,1,2,2,4,null,3,6,1,3,4,2,3]
      }
    },
    {
      "code": "00310",
      "name": "Kivihaka",
      "zone": 2,
      "price": {
        "studio": [2951,3794,3770,3893,4346,4220,4150,4732,5331,null,5823,6326,null,null,5439,null,null],
        "two": [2564,3605,2857,3456,3252,3252,3490,4161,4381,4366,4109,null,4921,4886,null,4125,null],
        "three": [2962,3196,3525,3370,3284,3373,3183,3768,3866,4094,3926,3990,4663,3385,4131,null,3982],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [11,17,10,16,12,10,11,8,7,5,8,6,2,2,6,4,5],
        "two": [7,14,7,9,11,9,8,12,8,6,11,5,12,14,6,7,3],
        "three": [7,13,10,15,9,7,10,10,8,12,14,9,13,6,9,5,12],
        "terraced": [2,1,null,3,3,null,null,null,null,null,null,null,2,null,null,null,null]
      }
    },
    {
      "code": "00320",
      "name": "Etelä-Haaga",
      "zone": 2,
      "price": {
        "studio": [3748,4036,4289,4646,4745,5050,5238,5511,5676,5856,6442,6952,6796,6581,5738,5342,5004],
        "two": [3011,3431,3626,3767,4068,4168,4351,4542,4394,4963,4870,5155,5681,5650,5076,4955,4948],
        "three": [2957,3397,3537,3621,3854,3837,4053,4124,4394,4614,4719,5054,5425,5329,4996,4928,5029],
        "terraced": [null,null,null,3999,null,null,null,null,3767,null,null,null,null,5228,null,null,null]
      },
      "count": {
        "studio": [103,126,116,98,90,101,96,71,66,81,105,87,106,63,49,100,54],
        "two": [131,134,139,117,121,132,116,115,124,122,175,145,161,94,97,131,85],
        "three": [70,84,71,68,60,75,77,75,85,79,108,110,100,81,84,81,87],
        "terraced": [5,6,8,9,2,2,5,3,8,4,4,8,11,7,5,7,6]
      }
    },
    {
      "code": "00330",
      "name": "Munkkiniemi",
      "zone": 2,
      "price": {
        "studio": [4259,4693,5080,5359,5637,5348,5896,5768,6167,6361,6663,7750,7280,7274,6360,6485,6752],
        "two": [3840,4224,4501,4632,4955,5069,5105,5221,5340,5819,5839,6265,6948,6938,6496,6139,6111],
        "three": [3959,4314,4455,4730,4911,4818,5092,5000,5382,5561,5754,6262,6726,7378,6797,6406,6358],
        "terraced": [null,null,null,null,null,null,null,null,5163,5810,5799,7154,null,null,null,7341,null]
      },
      "count": {
        "studio": [21,29,18,24,24,29,36,36,25,30,25,30,32,23,18,25,30],
        "two": [70,52,64,66,71,55,69,58,77,84,72,95,70,82,67,57,73],
        "three": [81,99,81,81,75,93,71,93,110,102,100,85,117,93,84,80,116],
        "terraced": [6,8,2,7,6,5,5,4,9,8,7,9,6,4,7,10,3]
      }
    },
    {
      "code": "00340",
      "name": "Kuusisaari - Lehtisaari",
      "zone": 2,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,3054,3524,null,null,3608,3598,4039,null,4663,3948,4455,4483,4569,null,null,3520],
        "three": [3268,3870,null,4154,3603,3254,3729,3848,4038,4300,4606,3873,4834,4851,3943,4442,3173],
        "terraced": [null,null,null,5178,4984,null,5533,null,null,null,null,null,4732,4943,4930,4381,4805]
      },
      "count": {
        "studio": [null,1,1,1,1,1,2,1,3,2,3,2,2,1,2,null,1],
        "two": [4,9,6,5,5,8,6,7,1,7,6,8,13,9,4,1,6],
        "three": [13,16,6,11,12,9,15,12,17,16,8,18,27,10,6,11,10],
        "terraced": [8,11,13,12,18,11,9,8,2,10,6,14,19,19,11,11,14]
      }
    },
    {
      "code": "00350",
      "name": "Munkkivuori - Niemenmäki",
      "zone": 3,
      "price": {
        "studio": [3653,4024,4013,4531,4918,4806,4864,4802,5117,4990,5455,6227,6365,6441,5456,4908,4668],
        "two": [3078,3429,3626,3925,4049,4057,4231,4434,4565,4506,4813,5011,5426,5421,4940,4689,4475],
        "three": [2943,3387,3630,3789,3872,3908,3875,4128,4257,4175,4533,4735,5252,5574,4945,4703,4748],
        "terraced": [null,null,null,null,4406,4113,4439,4156,4430,4290,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [54,50,42,40,27,17,32,28,34,42,35,41,53,40,27,34,41],
        "two": [92,81,65,80,72,58,67,61,88,65,82,79,77,90,73,42,58],
        "three": [71,73,63,64,65,62,78,67,93,75,101,83,76,98,58,88,69],
        "terraced": [5,3,null,3,12,13,21,19,10,12,7,8,4,6,2,4,7]
      }
    },
    {
      "code": "00360",
      "name": "Pajamäki",
      "zone": 3,
      "price": {
        "studio": [3021,3559,3385,3416,null,3902,4434,5214,4622,4958,5432,5255,5820,5508,4662,null,4183],
        "two": [2423,2748,2969,3165,3325,3503,3459,3739,3636,4077,4430,4420,4628,4494,4190,3837,3966],
        "three": [2474,2878,3022,3142,3153,3198,3019,3351,3649,3985,4221,4396,4815,4134,3993,3810,3664],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [16,12,11,20,4,7,10,9,11,10,13,13,10,15,8,5,7],
        "two": [35,28,35,26,29,30,20,35,19,13,18,24,33,27,20,13,9],
        "three": [16,19,22,22,14,27,18,15,18,15,35,21,13,13,10,9,16],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00370",
      "name": "Reimarla",
      "zone": 3,
      "price": {
        "studio": [3088,3432,3597,3602,3796,3971,4135,4064,3971,4141,4086,4180,4527,3851,null,3753,null],
        "two": [2757,3006,3152,3251,3243,2926,3168,3317,3483,3310,3227,3425,3641,4000,3718,3564,3257],
        "three": [2468,2675,2803,2971,3032,2820,2872,2946,2727,2863,2955,2769,3137,3351,3282,2827,3311],
        "terraced": [2987,3289,3563,3535,3725,3418,3196,3403,3122,3292,null,3581,3613,null,2976,3084,3241]
      },
      "count": {
        "studio": [23,17,20,17,15,19,23,14,14,10,11,42,14,19,6,13,6],
        "two": [31,26,33,31,23,33,27,24,27,15,27,60,34,29,15,17,20],
        "three": [19,22,28,16,12,15,24,19,16,23,21,35,34,13,16,16,19],
        "terraced": [19,25,18,19,19,19,10,12,7,11,6,15,14,5,8,8,10]
      }
    },
    {
      "code": "00380",
      "name": "Pitäjänmäen yritysalue",
      "zone": 2,
      "price": {
        "studio": [3905,4704,null,4640,null,5137,4775,5098,5160,5412,5248,5426,5526,5813,null,null,null],
        "two": [3915,3810,4247,4284,4613,4929,4469,4698,4848,5257,5091,4964,5767,5628,4995,5375,4377],
        "three": [3450,3696,3974,3988,4099,4120,4170,4297,4466,4704,4782,5063,5229,5518,5655,5049,4733],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [29,8,5,12,5,15,17,11,8,9,12,13,10,10,8,8,12],
        "two": [12,21,11,23,32,37,18,17,17,15,41,22,21,23,19,15,15],
        "three": [15,16,15,21,20,18,17,24,25,21,40,17,17,30,15,33,20],
        "terraced": [null,null,null,2,null,null,null,null,1,1,3,null,null,3,null,1,null]
      }
    },
    {
      "code": "00390",
      "name": "Konala",
      "zone": 4,
      "price": {
        "studio": [2880,3251,3334,3530,3708,4076,3939,4272,4363,4506,4462,4518,4946,4602,4290,4094,3434],
        "two": [2469,2708,2697,2902,2854,2989,3037,3077,3168,3275,3453,3653,3829,3787,3676,3338,3120],
        "three": [2183,2379,2510,2433,2747,2631,2824,2916,3147,2919,3190,3392,3676,3686,3386,3321,3470],
        "terraced": [2540,2712,2897,3060,2940,2986,3069,3298,3310,3132,2920,3337,3689,3602,3308,3203,2824]
      },
      "count": {
        "studio": [13,12,21,21,19,13,24,16,23,16,21,18,27,17,15,15,12],
        "two": [52,49,49,51,54,35,39,47,38,35,46,50,50,38,25,27,32],
        "three": [28,22,17,28,20,20,27,27,29,25,57,44,45,28,15,22,20],
        "terraced": [24,26,16,28,26,15,15,18,27,20,18,30,33,30,17,21,20]
      }
    },
    {
      "code": "00400",
      "name": "Pohjois-Haaga",
      "zone": 3,
      "price": {
        "studio": [3420,3729,4027,4323,4583,4713,4880,4631,4937,5522,5225,6223,6289,5556,5189,4668,4662],
        "two": [2737,3067,3235,3404,3603,3623,3792,3779,4218,4214,4403,4482,4934,4683,4396,3939,4167],
        "three": [2415,2833,3063,3107,3384,3276,3356,3377,3511,3573,3760,4093,4236,4441,4460,4175,3872],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [34,49,42,38,29,35,40,21,26,26,19,25,37,36,21,29,22],
        "two": [101,104,111,104,83,71,81,84,74,103,74,77,89,76,45,63,65],
        "three": [71,84,83,67,69,58,72,66,65,68,73,94,108,79,62,60,55],
        "terraced": [null,null,null,1,3,1,null,null,null,2,1,3,null,1,1,1,2]
      }
    },
    {
      "code": "00410",
      "name": "Malminkartano",
      "zone": 4,
      "price": {
        "studio": [null,null,3170,null,null,null,null,null,3496,3564,4135,3511,4212,4273,3537,null,2907],
        "two": [2345,2472,2612,2695,2857,2675,2731,2635,2772,2904,2777,3462,3304,3185,2795,2494,2085],
        "three": [2037,2399,2454,2509,2498,2458,2400,2435,2507,2749,2708,2596,2601,2669,2577,2572,2229],
        "terraced": [2281,2540,2526,2576,2694,2494,2423,2734,2775,2638,2716,3069,2770,3364,3900,3800,3243]
      },
      "count": {
        "studio": [5,6,8,7,4,5,5,8,11,11,9,8,16,9,9,5,8],
        "two": [33,39,32,35,26,30,27,40,33,30,36,32,40,37,28,22,22],
        "three": [36,32,32,48,35,28,30,34,33,46,42,39,40,37,30,11,14],
        "terraced": [9,13,13,10,10,9,13,12,18,8,12,16,15,13,22,17,18]
      }
    },
    {
      "code": "00420",
      "name": "Kannelmäki",
      "zone": 4,
      "price": {
        "studio": [2988,3231,3472,3587,3774,3785,4158,3995,4284,4584,4393,4364,4682,4352,3758,3751,3763],
        "two": [2333,2692,2655,2699,2963,2914,3070,2961,3343,3348,3497,3405,3680,3314,3135,2939,2985],
        "three": [2175,2380,2336,2483,2556,2712,2654,2583,2921,3090,3029,3062,3152,3001,2771,2667,2681],
        "terraced": [2579,2804,2949,3100,2933,2779,2793,2530,2538,2860,2594,2531,2834,2997,2042,2657,2775]
      },
      "count": {
        "studio": [36,61,43,44,38,40,63,37,25,35,38,23,43,42,35,21,25],
        "two": [99,97,99,104,80,78,82,108,95,73,84,87,91,115,60,52,52],
        "three": [65,77,84,83,58,59,54,90,83,60,73,68,80,90,43,44,71],
        "terraced": [17,13,19,17,24,21,18,21,20,21,19,33,38,25,6,17,16]
      }
    },
    {
      "code": "00430",
      "name": "Maununneva - Kuninkaantammi",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,4370,4736,4114,null,4074],
        "three": [null,null,null,null,null,null,null,null,null,null,null,4052,4236,3852,3836,4149,3780],
        "terraced": [2589,3327,3412,2984,3154,3377,3423,3388,2937,3342,3547,3671,3847,3938,3940,3396,3358]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,2,27,2,20,5],
        "two": [1,3,1,3,1,2,2,1,null,null,2,8,15,20,6,19,18],
        "three": [6,6,3,4,1,2,1,3,3,7,3,10,18,25,16,27,9],
        "terraced": [28,19,19,20,20,26,29,26,22,29,45,25,50,30,27,29,35]
      }
    },
    {
      "code": "00440",
      "name": "Lassila",
      "zone": 3,
      "price": {
        "studio": [3583,3791,3922,4197,4250,4514,4113,4336,4424,4789,4670,4608,4775,4588,3871,4416,3820],
        "two": [2721,3009,3225,3312,3367,3424,3450,3589,3591,3836,3886,3883,4154,3800,3416,3316,3405],
        "three": [2515,2740,2992,2946,3083,3094,3155,3245,3306,3331,3404,3402,3884,3695,3197,3061,3043],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [18,16,38,17,20,34,30,20,25,20,35,34,26,12,13,12,14],
        "two": [38,22,33,31,29,28,38,45,34,28,45,52,58,25,23,23,15],
        "three": [27,35,37,53,35,34,48,30,45,41,41,43,54,42,28,19,21],
        "terraced": [1,4,1,2,1,null,2,4,2,3,4,2,2,1,4,1,2]
      }
    },
    {
      "code": "00500",
      "name": "Sörnäinen - Harju",
      "zone": 2,
      "price": {
        "studio": [3821,4246,4534,4744,5217,5329,5507,5846,6145,6383,6633,7037,7341,7116,6095,6009,5302],
        "two": [3392,3909,4094,4272,4528,4700,4862,5155,5335,5682,5921,6200,6559,6513,5493,5283,5173],
        "three": [3454,3798,3914,3956,4066,4302,4534,4739,4820,5056,5590,5839,5899,6317,5989,5291,5032],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [394,363,287,332,261,253,327,272,278,269,240,263,278,252,171,145,166],
        "two": [164,190,157,133,138,120,119,149,151,100,192,163,171,106,91,76,73],
        "three": [33,34,38,40,27,23,35,26,18,26,45,40,33,23,19,19,19],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00510",
      "name": "Alppila - Vallila",
      "zone": 2,
      "price": {
        "studio": [3821,4295,4547,4748,4970,5203,5402,5495,6166,6436,6524,7070,7260,7077,6279,6141,5490],
        "two": [3386,3800,4011,4161,4546,4548,4668,4950,5259,5734,5811,6129,6628,6667,5710,5470,5369],
        "three": [3464,3542,3768,4012,4247,4559,4742,4707,5021,5166,6080,6027,6541,6791,6263,5981,5676],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [223,239,214,203,193,152,166,150,158,147,137,144,220,163,114,95,114],
        "two": [135,134,140,135,103,102,124,107,127,126,123,132,134,113,97,76,84],
        "three": [26,25,18,15,17,15,41,25,38,31,34,28,54,43,33,30,34],
        "terraced": [2,null,1,null,null,1,null,null,null,null,null,2,null,null,null,1,null]
      }
    },
    {
      "code": "00520",
      "name": "Itä- ja Keski-Pasila",
      "zone": 2,
      "price": {
        "studio": [3607,4147,4454,4798,4916,5105,5439,5532,5840,5785,6208,6818,7115,6680,6002,6382,6210],
        "two": [3141,3490,3648,3911,4369,4238,4487,4678,5385,5605,5316,5757,6194,6444,6010,5187,5651],
        "three": [2823,3184,3710,3729,4426,4179,4473,4595,4674,5465,5450,5525,5622,5755,5598,5445,5190],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [31,56,33,44,25,30,43,25,31,41,32,34,41,41,28,35,31],
        "two": [64,79,47,77,59,45,60,59,54,56,73,85,78,86,81,61,73],
        "three": [23,56,36,56,45,56,49,46,58,60,83,77,109,83,61,57,86],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00530",
      "name": "Kallio",
      "zone": 2,
      "price": {
        "studio": [4017,4407,4637,4994,5354,5469,5501,5666,6067,6245,6723,7083,7406,7145,6554,6188,5743],
        "two": [3669,4035,4324,4473,4781,4907,5052,5114,5459,5806,6030,6282,6613,6485,5921,5591,5470],
        "three": [3720,3955,4341,4515,4525,4694,4894,4864,5167,5618,5685,6117,6383,6324,5905,5582,5817],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [331,299,293,258,290,243,256,237,220,216,258,279,299,199,157,186,159],
        "two": [241,231,186,211,223,165,215,197,189,213,216,214,273,202,176,162,177],
        "three": [76,70,56,50,78,69,67,63,67,65,63,78,89,57,53,70,72],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00540",
      "name": "Kalasatama - Sompasaari",
      "zone": 2,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,8321,null,9009,9156],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,8344,8796,8224,7497,7966],
        "three": [null,null,null,null,null,null,5775,null,6252,null,6896,null,7892,7779,7705,7811,7160],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [null,null,null,null,null,null,1,2,2,2,4,4,6,10,34,14,8],
        "two": [null,null,null,null,null,null,4,1,8,12,10,10,21,25,32,18,22],
        "three": [null,null,null,null,null,null,26,9,11,12,17,13,19,39,63,51,52],
        "terraced": [null,null,null,null,null,null,null,null,null,1,2,null,1,null,null,null,1]
      }
    },
    {
      "code": "00550",
      "name": "Vallila - Hermanni",
      "zone": 2,
      "price": {
        "studio": [3646,3993,4234,4380,4765,5039,5219,5283,5551,5865,6135,6458,7014,6673,5754,6006,5525],
        "two": [3134,3574,3802,3948,4263,4282,4536,4611,5005,5388,5644,5997,6291,5936,5647,5377,5148],
        "three": [3306,3730,3692,3892,4161,4057,4130,4187,4687,5157,4846,5455,6034,6168,5672,5363,5333],
        "terraced": [null,4421,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [106,98,84,108,79,61,91,92,87,88,140,106,121,84,47,47,52],
        "two": [117,132,107,110,85,90,82,78,80,94,114,107,104,89,62,62,66],
        "three": [19,41,30,20,30,27,37,26,18,23,19,25,28,22,29,34,24],
        "terraced": [5,6,2,1,1,1,null,3,null,null,2,null,1,1,null,1,1]
      }
    },
    {
      "code": "00560",
      "name": "Toukola - Kumpula - Vanhakaupunki",
      "zone": 2,
      "price": {
        "studio": [3794,3878,4532,4618,5434,4610,5365,5813,5272,5845,6840,6956,6347,6490,5909,5763,5584],
        "two": [3831,4356,4506,4571,4843,5065,4910,5291,5541,5471,5649,5953,6391,6263,5882,5467,5387],
        "three": [3943,4326,4534,4828,4928,4963,4857,5043,5318,5315,5457,6016,6243,6400,5827,5758,5354],
        "terraced": [3285,3893,null,null,4410,5040,null,4845,4586,4606,null,5673,5563,6081,6177,null,null]
      },
      "count": {
        "studio": [26,22,35,31,16,29,31,28,25,24,38,22,36,25,18,28,22],
        "two": [61,68,81,86,69,83,82,73,90,78,80,88,89,75,71,61,83],
        "three": [36,50,71,81,50,85,76,74,76,72,69,95,101,73,75,48,85],
        "terraced": [8,14,5,5,6,8,5,11,8,16,7,11,13,7,10,5,6]
      }
    },
    {
      "code": "00570",
      "name": "Kulosaari",
      "zone": 2,
      "price": {
        "studio": [3845,4202,4449,4539,4920,5006,5174,5546,5858,6375,6345,6771,7212,7233,6637,5767,5747],
        "two": [3354,3679,3641,4158,4237,4159,4520,4494,5155,5537,5523,5706,5933,6863,5585,5359,5380],
        "three": [3390,3623,3745,3800,4023,3951,4328,4400,4709,5280,5193,5400,6372,6073,5551,5288,5209],
        "terraced": [null,null,null,5115,null,null,null,4554,5065,5226,5752,6107,5770,7326,5566,6408,5744]
      },
      "count": {
        "studio": [16,18,15,20,14,20,17,10,16,13,10,16,17,14,9,11,13],
        "two": [25,26,24,23,22,24,16,29,20,14,20,27,26,21,21,18,18],
        "three": [41,34,43,37,28,32,33,46,30,37,38,34,30,45,23,35,37],
        "terraced": [8,11,7,13,11,5,7,11,16,11,16,18,35,30,9,13,13]
      }
    },
    {
      "code": "00580",
      "name": "Kalasatama - Kyläsaari",
      "zone": 2,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,9561,8776,8845,7939],
        "two": [null,null,null,null,null,null,null,null,null,6315,null,null,8191,8540,8155,8206,7066],
        "three": [null,null,null,4399,4081,null,4841,5001,null,null,6318,6896,6636,7639,7163,7594,7455],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [2,null,1,null,3,2,3,null,4,1,3,1,null,13,28,28,20],
        "two": [null,1,3,4,3,7,7,6,6,12,7,6,8,35,51,66,51],
        "three": [null,2,7,11,11,13,16,13,8,7,18,17,18,41,46,76,49],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,3,1,null,null]
      }
    },
    {
      "code": "00590",
      "name": "Kruunuvuorenranta",
      "zone": 2,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,8089,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,5743,null,5408,6036,null],
        "three": [null,null,null,null,null,null,null,null,null,null,4756,4752,5293,5748,5435,6705,5199],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,2,4,8,2,2,5,4],
        "two": [null,null,null,null,null,null,null,null,null,2,3,6,14,7,10,16,7],
        "three": [null,null,null,null,null,null,null,null,null,2,13,25,31,25,18,19,34],
        "terraced": [1,1,null,3,4,null,2,2,3,1,3,3,4,1,6,4,4]
      }
    },
    {
      "code": "00600",
      "name": "Koskela",
      "zone": 4,
      "price": {
        "studio": [3002,3275,null,3754,null,3963,null,null,4340,null,4459,null,null,4840,null,null,4140],
        "two": [2660,2589,2728,2781,2709,2959,2626,3152,3307,3026,2985,3470,3305,4099,3614,null,3586],
        "three": [2391,2411,2785,2450,null,null,3064,2745,2573,2506,2901,3036,3370,2979,3092,2757,2803],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [9,9,5,16,6,6,4,3,9,3,10,5,6,10,9,7,9],
        "two": [6,11,17,22,6,9,16,8,11,19,18,11,16,13,13,9,11],
        "three": [10,13,7,12,4,6,13,12,18,18,19,16,13,15,17,13,20],
        "terraced": [1,null,null,2,null,null,null,3,1,1,1,null,4,2,1,null,null]
      }
    },
    {
      "code": "00610",
      "name": "Käpylä",
      "zone": 2,
      "price": {
        "studio": [3665,3832,4497,4348,4569,4906,4898,5228,5085,5392,5509,6157,6292,5988,5525,5826,4665],
        "two": [3353,3658,3863,4182,4360,4591,4568,4679,5038,5156,5419,5631,5950,5912,5294,5198,4879],
        "three": [2946,3524,3835,3953,4033,4310,4234,4485,4580,4790,5136,5520,5874,5639,5240,5069,5085],
        "terraced": [null,null,null,null,null,6041,null,5819,6378,5487,null,7063,6155,8310,6451,6718,6665]
      },
      "count": {
        "studio": [25,18,26,26,22,23,28,23,30,32,45,36,42,54,25,16,33],
        "two": [60,64,67,63,56,59,57,82,71,64,84,70,79,68,49,53,56],
        "three": [45,50,42,51,44,37,62,51,48,44,53,71,61,64,29,40,49],
        "terraced": [5,4,1,2,6,10,6,12,9,11,5,10,10,11,10,11,15]
      }
    },
    {
      "code": "00620",
      "name": "Metsälä - Etelä-Oulunkylä",
      "zone": 3,
      "price": {
        "studio": [3137,3320,null,3669,null,4494,3977,null,null,5165,null,null,null,null,null,null,null],
        "two": [2725,2878,3041,3164,3573,3838,3639,3610,3942,4070,4191,4575,4564,4659,3820,3747,3717],
        "three": [2486,2796,2886,2770,3029,3554,3482,3569,3852,3799,3830,4407,4398,4408,4204,4130,3820],
        "terraced": [null,3324,3223,3032,3167,3395,3489,3691,3554,3283,3464,3808,3804,4345,3609,3536,4013]
      },
      "count": {
        "studio": [8,11,5,8,1,7,6,4,5,6,2,4,3,5,5,2,4],
        "two": [24,23,34,29,30,28,21,20,26,20,33,21,25,32,22,12,14],
        "three": [10,10,21,28,22,12,19,23,13,24,16,29,27,34,23,27,28],
        "terraced": [11,14,13,11,10,10,12,13,11,15,14,28,23,17,21,18,16]
      }
    },
    {
      "code": "00630",
      "name": "Maunula",
      "zone": 4,
      "price": {
        "studio": [2974,3341,3241,3836,3885,3990,4385,4540,4710,4901,5084,5606,5358,5157,4598,4240,3995],
        "two": [2352,2545,2670,3054,3182,3271,3346,3451,3608,3825,3823,4056,4038,4144,3935,3638,3499],
        "three": [2217,2354,2478,2514,2673,2866,2968,2906,3120,3428,3253,3284,3735,3745,3818,3574,3036],
        "terraced": [null,null,null,null,3677,null,3602,3660,4180,4292,null,4513,4623,5086,5147,4650,4283]
      },
      "count": {
        "studio": [27,15,34,19,22,15,28,18,13,17,12,19,13,12,18,10,10],
        "two": [40,53,61,55,47,41,42,57,44,34,35,54,54,48,27,31,22],
        "three": [47,31,36,41,21,34,28,33,29,50,40,32,43,30,36,34,19],
        "terraced": [4,2,7,2,9,7,15,9,10,13,9,9,11,17,15,15,10]
      }
    },
    {
      "code": "00640",
      "name": "Oulunkylä - Patola",
      "zone": 4,
      "price": {
        "studio": [3084,3216,3345,3737,3812,4036,4403,3926,4360,4716,4775,5400,5000,5068,4174,4142,4485],
        "two": [2576,2850,2972,3127,3243,3041,3157,3314,3389,3475,3666,3890,4182,3655,3701,3359,3461],
        "three": [2458,2716,2895,2806,2842,3057,3095,3115,3272,3616,3270,3637,3960,3775,3477,3480,3597],
        "terraced": [2859,3158,3239,3271,3446,3447,3207,3596,3452,3545,3562,3915,4310,4213,4158,3784,3966]
      },
      "count": {
        "studio": [29,29,25,30,25,23,17,25,15,21,22,23,27,22,15,14,16],
        "two": [65,62,80,73,47,48,58,63,56,49,61,60,69,65,44,55,50],
        "three": [27,37,60,48,47,47,44,47,49,56,49,46,65,48,39,51,41],
        "terraced": [21,20,18,23,19,16,33,28,26,23,21,39,46,42,26,28,31]
      }
    },
    {
      "code": "00650",
      "name": "Veräjämäki",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [2675,2798,2913,null,3376,null,3172,3588,null,null,3663,3695,3909,4139,3772,null,4072],
        "three": [2451,2894,null,3293,3108,3092,3123,3202,3112,3526,3515,3728,3645,3580,3404,4204,4319],
        "terraced": [2998,3217,3505,3691,3384,3595,3731,3779,3232,3551,3942,3506,3883,4659,4399,3560,3980]
      },
      "count": {
        "studio": [2,2,null,null,null,2,2,1,3,2,3,4,null,3,1,1,3],
        "two": [13,7,12,6,10,4,8,12,10,7,10,19,18,12,14,6,11],
        "three": [9,10,5,12,8,7,15,9,16,14,15,11,8,20,11,17,36],
        "terraced": [21,17,15,13,14,16,12,18,24,14,19,27,27,35,17,14,23]
      }
    },
    {
      "code": "00660",
      "name": "Länsi-Pakila",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,5389,null,null,null,null,null,null],
        "two": [null,2572,null,2714,2615,null,null,null,null,null,4231,4751,null,null,null,null,null],
        "three": [null,null,null,null,null,3096,null,null,3050,null,null,null,null,null,null,null,null],
        "terraced": [3053,3487,3562,3418,3720,3538,3435,3471,3495,3673,3687,3700,4203,4319,4048,3752,4161]
      },
      "count": {
        "studio": [1,2,4,4,2,1,3,1,4,3,6,2,4,4,1,2,6],
        "two": [5,6,5,9,11,2,4,3,3,5,6,8,4,2,4,3,5],
        "three": [3,1,3,5,4,6,2,1,6,2,1,4,3,2,5,2,5],
        "terraced": [48,72,53,63,52,40,72,71,70,60,74,88,108,138,76,75,79]
      }
    },
    {
      "code": "00670",
      "name": "Paloheinä",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "terraced": [2937,3379,3525,3455,3527,3458,3566,3510,3603,3655,3631,4077,4246,4393,3852,3917,3746]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [3,null,null,1,2,2,null,1,null,1,2,1,null,1,null,1,null],
        "three": [1,1,null,null,1,null,null,null,1,null,1,null,null,null,null,null,null],
        "terraced": [64,63,61,69,73,75,53,61,57,80,85,99,101,88,48,62,80]
      }
    },
    {
      "code": "00680",
      "name": "Itä-Pakila",
      "zone": 3,
      "price": {
        "studio": [null,3102,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,null,3325,null,null,null,null,null,null],
        "terraced": [2846,3302,3245,3358,3458,3139,3135,3398,3441,3260,3480,3427,3996,4055,4060,3806,3498]
      },
      "count": {
        "studio": [3,6,2,1,2,null,null,1,null,null,1,null,null,null,null,1,null],
        "two": [5,1,1,null,2,2,2,1,6,2,1,null,2,null,null,null,null],
        "three": [null,3,null,3,null,1,null,1,5,4,6,3,2,2,null,2,1],
        "terraced": [37,30,28,46,42,27,38,45,44,31,47,59,75,32,21,62,48]
      }
    },
    {
      "code": "00690",
      "name": "Torpparinmäki",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "terraced": [2752,null,3097,3142,3174,3016,null,3169,3123,3193,3178,3753,3578,3782,3282,3052,3434]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [5,1,2,4,7,1,null,2,3,3,2,2,null,3,4,null,2],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,4,null,null,null,null],
        "terraced": [28,21,19,26,13,19,10,24,29,29,26,29,15,29,17,8,14]
      }
    },
    {
      "code": "00700",
      "name": "Malmi",
      "zone": 4,
      "price": {
        "studio": [3149,3472,3399,3768,3760,3860,3898,4002,4125,3966,3996,4060,4698,4354,4012,3585,3590],
        "two": [2530,2787,2896,2910,3013,3037,3204,3202,3380,3137,3222,3414,3400,3396,3135,3033,2819],
        "three": [2306,2550,2631,2605,2747,2579,2613,2705,2780,2651,2834,3025,3024,2932,2650,2764,2642],
        "terraced": [2835,3189,3258,3141,3086,3215,3009,3271,3362,3372,3350,3300,3269,3565,3593,3093,3290]
      },
      "count": {
        "studio": [34,30,26,27,30,31,42,20,20,25,16,30,23,24,23,15,14],
        "two": [64,63,64,48,61,58,58,72,57,60,57,64,81,64,72,35,42],
        "three": [46,50,38,42,46,39,53,40,43,34,41,33,51,52,62,42,34],
        "terraced": [26,34,34,29,35,22,32,26,29,42,40,33,49,37,26,24,26]
      }
    },
    {
      "code": "00710",
      "name": "Pihlajamäki - Viikinmäki",
      "zone": 4,
      "price": {
        "studio": [2502,3123,2909,3299,3026,3250,3452,3539,3585,3920,3746,4069,4040,4179,4301,3345,3087],
        "two": [2193,2443,2392,2612,2484,2530,2594,2552,2731,2783,2779,2794,2969,2957,3074,2701,2411],
        "three": [1930,2490,2350,2286,2445,2426,2385,2335,2351,2491,2562,2593,2710,2680,2574,2133,2252],
        "terraced": [null,2779,2820,2666,2797,3285,2904,2847,3182,3305,3622,3345,3295,3586,3167,3950,3206]
      },
      "count": {
        "studio": [25,25,32,27,22,17,24,23,29,30,24,56,25,23,16,17,58],
        "two": [81,86,80,88,81,79,71,93,78,69,78,173,94,63,61,57,60],
        "three": [65,70,70,97,64,72,57,76,70,78,78,115,85,79,51,62,56],
        "terraced": [12,13,12,15,17,13,17,14,16,20,18,33,14,14,16,19,20]
      }
    },
    {
      "code": "00720",
      "name": "Pukinmäki",
      "zone": 4,
      "price": {
        "studio": [3119,3612,3697,4019,4055,4158,3896,4253,4243,4009,4093,4702,4349,4201,4146,4074,3533],
        "two": [2533,2676,2893,3017,3195,3105,3137,2987,3046,3248,3183,3230,3487,3422,3029,2792,2481],
        "three": [2283,2492,2615,2634,2737,2748,2675,2623,2686,2860,2929,3060,3064,3155,2995,2897,2621],
        "terraced": [2643,3068,2944,3089,3090,2964,2994,3048,2990,3136,3112,3254,3533,3391,3279,3191,2810]
      },
      "count": {
        "studio": [24,25,25,19,20,18,22,21,16,14,25,23,24,16,13,14,12],
        "two": [54,58,54,43,55,57,47,64,56,61,39,51,51,53,33,24,30],
        "three": [53,49,44,44,53,38,49,60,56,64,40,58,70,52,39,33,34],
        "terraced": [19,13,20,13,12,15,17,17,17,12,20,22,17,17,14,24,14]
      }
    },
    {
      "code": "00730",
      "name": "Tapanila",
      "zone": 3,
      "price": {
        "studio": [3662,3634,3549,3539,4109,4360,3852,null,4478,null,3620,5268,5275,4617,4691,3998,4338],
        "two": [2612,2985,2976,2977,3183,3321,3286,3061,3085,3309,3459,3522,3648,3663,2962,3366,3997],
        "three": [2275,2594,2699,3005,3150,3091,3049,2817,2870,3358,2831,3406,3352,3695,3092,3326,3409],
        "terraced": [2787,3059,3179,3074,3278,3170,3247,3347,3169,3353,3533,3371,3571,3750,3532,3435,3241]
      },
      "count": {
        "studio": [20,14,20,12,14,12,14,4,7,6,12,24,18,10,7,10,13],
        "two": [45,51,43,41,32,26,31,26,28,33,38,26,41,32,20,18,33],
        "three": [26,16,25,28,22,17,23,17,14,22,20,22,26,17,15,13,60],
        "terraced": [64,77,65,87,58,57,77,79,70,77,65,92,98,91,55,70,75]
      }
    },
    {
      "code": "00740",
      "name": "Siltamäki",
      "zone": 4,
      "price": {
        "studio": [2906,3231,3322,3380,3618,3555,3545,null,3625,null,3502,3951,3670,3576,3636,null,2510],
        "two": [2075,2380,2436,2440,2432,2545,2298,2356,2267,2302,2497,2363,2295,2626,2381,2188,1798],
        "three": [2158,2179,2266,2134,1992,2119,2092,2043,2094,2199,2269,2297,2307,2587,2375,2114,1737],
        "terraced": [2516,2743,2999,2887,2974,2963,2972,2923,2963,3004,3048,3144,3260,3180,3205,2958,3033]
      },
      "count": {
        "studio": [6,7,6,11,12,12,11,5,10,5,12,8,9,10,8,4,7],
        "two": [34,32,22,30,27,28,27,28,33,22,30,43,35,33,18,25,24],
        "three": [23,18,22,31,31,25,28,35,31,32,27,49,52,23,31,20,22],
        "terraced": [77,60,65,55,47,50,46,50,57,71,56,66,68,67,48,60,63]
      }
    },
    {
      "code": "00750",
      "name": "Tapulikaupunki",
      "zone": 4,
      "price": {
        "studio": [null,3189,2818,3287,null,null,3512,null,3479,null,3723,null,null,null,null,null,null],
        "two": [2196,2607,2285,2390,2400,2639,2589,2577,2572,2618,2703,2394,2730,2331,2271,2104,1962],
        "three": [1909,2086,2218,2144,2426,2228,2093,2285,2156,2094,2159,2288,2233,1955,1968,1909,2250],
        "terraced": [2536,2911,2978,2915,2988,3051,3001,3121,2965,3058,3003,3047,3099,3295,2830,2993,2973]
      },
      "count": {
        "studio": [2,6,8,8,5,3,12,5,6,5,9,3,4,5,4,2,3],
        "two": [28,23,24,21,22,24,22,21,20,21,18,23,21,16,7,10,11],
        "three": [24,23,24,17,10,23,28,19,18,18,12,22,24,16,9,20,13],
        "terraced": [39,45,30,56,32,31,48,29,47,23,48,43,42,43,26,21,22]
      }
    },
    {
      "code": "00760",
      "name": "Puistola - Heikinlaakso",
      "zone": 4,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [2222,1946,2178,null,2450,null,null,2679,null,2481,2618,null,null,null,null,1878,null],
        "three": [1953,null,2344,null,2310,2252,2580,null,2466,2399,2370,null,2306,null,2498,null,null],
        "terraced": [2560,2816,2904,2918,3057,2853,2923,3044,3010,3001,3013,3000,3141,3203,2931,2771,3019]
      },
      "count": {
        "studio": [2,4,1,null,3,3,3,3,2,2,2,2,2,null,1,1,1],
        "two": [8,7,11,3,8,5,4,6,5,9,7,3,4,4,3,8,2],
        "three": [7,4,8,5,7,9,8,2,6,6,9,3,6,2,6,5,4],
        "terraced": [73,68,80,73,51,67,58,55,56,73,63,84,106,72,49,53,53]
      }
    },
    {
      "code": "00770",
      "name": "Jakomäki - Alppikylä",
      "zone": 4,
      "price": {
        "studio": [null,null,null,null,null,null,null,2714,null,null,null,null,null,null,null,1957,null],
        "two": [1859,2029,2015,2217,2155,2205,2206,1919,2085,2061,1967,2216,1991,2113,2552,1558,null],
        "three": [1719,1744,1923,1946,1929,1899,1932,1799,1849,1820,1664,1596,1676,2193,2223,2137,2222],
        "terraced": [2690,2466,2500,null,null,null,null,null,3459,3263,3134,3530,3891,3829,3454,3461,3212]
      },
      "count": {
        "studio": [4,2,2,1,2,4,2,10,1,2,3,4,1,24,4,8,1],
        "two": [17,25,25,17,17,15,14,17,14,16,17,17,19,66,10,10,9],
        "three": [22,28,24,20,20,18,17,13,16,27,18,22,21,66,13,8,21],
        "terraced": [7,8,6,3,3,2,2,1,8,7,11,18,25,18,21,16,12]
      }
    },
    {
      "code": "00780",
      "name": "Tapaninvainio",
      "zone": 3,
      "price": {
        "studio": [null,3172,3711,3840,null,null,4143,3667,4203,4117,3808,null,3948,null,null,3464,3273],
        "two": [2667,2842,3112,3014,3033,3074,3086,3231,3220,3499,3339,3234,3329,3579,3175,2996,2879],
        "three": [2128,null,2473,2541,2466,2462,2650,2484,2705,2870,2713,2889,2909,3186,2769,2629,2354],
        "terraced": [2682,3128,3369,3163,3121,3245,3268,3232,3055,3199,3239,3427,3586,3602,3429,3279,3062]
      },
      "count": {
        "studio": [4,7,18,9,4,3,11,8,8,9,14,4,7,4,5,7,6],
        "two": [28,19,26,20,23,21,16,15,17,25,20,30,20,20,18,12,12],
        "three": [15,5,14,16,13,14,13,13,11,12,16,23,23,13,14,8,12],
        "terraced": [46,48,46,60,48,37,57,66,44,63,69,77,81,51,48,55,64]
      }
    },
    {
      "code": "00790",
      "name": "Viikki",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,4841,null,5088,null,4869,null,null,null,null,null,null,null,null],
        "two": [3341,3661,3754,3944,4153,4070,3997,4358,4470,4738,4769,4875,5076,5036,4461,4185,4491],
        "three": [3117,3390,3543,3537,3705,3703,3809,3657,3853,4278,4459,4359,4602,4654,4241,4019,3989],
        "terraced": [2901,3353,3429,3527,3623,3787,3768,3826,3977,4151,4322,4639,4550,4940,4572,4260,4096]
      },
      "count": {
        "studio": [4,3,10,4,8,6,7,4,6,4,34,5,4,4,5,1,20],
        "two": [41,35,52,24,29,33,35,35,42,30,70,39,42,34,33,21,43],
        "three": [43,45,54,55,55,51,60,36,52,41,89,68,59,49,45,25,36],
        "terraced": [18,17,17,15,16,14,20,22,22,23,18,22,27,16,18,12,16]
      }
    },
    {
      "code": "00800",
      "name": "Länsi-Herttoniemi",
      "zone": 3,
      "price": {
        "studio": [3174,3805,3846,4123,4232,4821,4594,4728,5090,5337,5438,6017,6234,5945,5663,5248,4756],
        "two": [2907,3159,3271,3457,3798,3981,4111,4287,4296,4794,4986,5521,5392,5648,4858,4874,4681],
        "three": [2680,3131,3347,3549,3501,3789,3720,4027,4118,4330,4683,5209,5233,5302,5215,5139,4741],
        "terraced": [3272,3615,3475,3539,3931,3387,3924,4561,4508,4843,null,5771,4853,null,null,6012,null]
      },
      "count": {
        "studio": [49,24,19,31,16,15,30,27,30,19,28,23,30,29,14,20,17],
        "two": [61,50,42,45,45,43,46,43,45,43,58,50,50,54,40,34,37],
        "three": [36,30,23,33,26,22,19,26,31,23,30,38,29,37,20,21,36],
        "terraced": [12,8,8,11,17,7,12,13,11,10,10,12,11,5,6,8,8]
      }
    },
    {
      "code": "00810",
      "name": "Herttoniemenranta",
      "zone": 2,
      "price": {
        "studio": [3204,3968,4011,4312,4586,4857,4595,5099,5140,5546,5665,6182,5498,5932,null,null,5379],
        "two": [3288,3768,3981,3935,4343,4441,4609,4701,4698,5011,5317,5619,5551,5856,5502,5391,5123],
        "three": [3134,3806,3621,3946,3911,4117,4081,4226,4605,4776,4919,5173,5484,5954,5325,4793,4971],
        "terraced": [null,4722,4570,4668,null,null,null,null,5102,null,null,null,5667,null,null,null,null]
      },
      "count": {
        "studio": [11,10,25,19,28,8,19,21,17,12,16,17,78,42,6,34,28],
        "two": [49,52,63,63,59,39,57,61,49,36,68,61,123,139,32,117,96],
        "three": [57,48,77,70,78,63,56,75,76,50,70,87,105,101,49,84,87],
        "terraced": [4,12,13,8,6,5,4,2,8,3,3,8,11,4,5,3,2]
      }
    },
    {
      "code": "00820",
      "name": "Roihuvuori",
      "zone": 4,
      "price": {
        "studio": [3121,3216,3432,3671,3570,3859,3844,4135,4550,4651,5048,4429,5941,5269,4461,4428,4096],
        "two": [2441,2628,2751,2868,2947,2971,2942,3027,3238,3472,3724,3861,4557,4700,3976,3845,3825],
        "three": [2144,2447,2505,2642,2642,2558,2622,2747,3028,3270,3375,3843,4185,4399,4052,3789,3722],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [23,21,25,21,17,22,26,18,19,18,15,16,17,17,11,14,15],
        "two": [76,75,73,80,65,50,33,55,47,54,55,57,75,70,47,46,64],
        "three": [64,76,80,67,68,69,55,55,68,59,69,65,69,76,64,55,75],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00830",
      "name": "Tammisalo",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [2821,null,3485,null,3488,3211,2869,3015,null,3741,3625,3627,3505,4213,null,null,null],
        "three": [3008,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "terraced": [3459,3682,3471,3828,3471,3913,3511,3532,3655,4207,3999,4154,4213,4309,4489,4090,4540]
      },
      "count": {
        "studio": [2,3,3,3,5,2,null,null,2,null,1,3,4,2,null,2,1],
        "two": [11,3,7,4,9,8,8,8,4,7,9,11,9,7,2,3,4],
        "three": [9,1,2,5,3,3,4,3,3,5,3,3,null,4,3,1,5],
        "terraced": [23,20,14,25,23,20,23,26,38,27,37,41,50,28,25,27,27]
      }
    },
    {
      "code": "00840",
      "name": "Yliskylä",
      "zone": 3,
      "price": {
        "studio": [3163,3576,3691,3882,4005,4180,4231,4194,4594,4615,4872,4602,4675,5051,4710,4404,4074],
        "two": [2612,2699,2910,3007,3111,3320,3130,3325,3350,3461,3726,3769,4110,4268,4034,3820,3500],
        "three": [2339,2698,2777,2789,2765,2715,2770,2992,3212,3118,3367,3452,3608,4142,3513,3432,3524],
        "terraced": [3296,3244,3373,3487,3438,3458,3607,3516,3575,3455,3489,3959,4317,4257,3894,3538,3850]
      },
      "count": {
        "studio": [26,23,32,25,16,21,31,28,27,14,18,28,19,19,16,18,15],
        "two": [38,47,50,61,51,38,42,38,55,53,44,42,58,41,32,48,45],
        "three": [48,67,45,70,62,44,61,60,70,73,61,76,89,53,43,60,63],
        "terraced": [34,53,33,55,29,37,45,35,59,56,57,60,48,39,52,35,53]
      }
    },
    {
      "code": "00850",
      "name": "Jollas",
      "zone": 2,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,4610,null,5059,null,null,null,null,null],
        "terraced": [4054,null,3377,3500,4346,4235,null,3345,3474,3639,3863,4183,4662,4302,4316,4072,4188]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [3,4,2,4,4,5,5,2,4,7,2,6,4,3,6,null,null],
        "terraced": [15,16,14,14,11,8,12,17,18,22,25,31,32,21,13,15,27]
      }
    },
    {
      "code": "00870",
      "name": "Gunillanmäki - Hevossalmi",
      "zone": 4,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,4090,null,null,null],
        "two": [2161,2404,2561,2702,2783,2560,2858,2814,2794,null,2848,2852,3081,3477,3062,null,2875],
        "three": [2166,2358,2465,2584,2570,2593,2470,2519,2388,2438,2147,2376,3173,3121,3904,3123,2722],
        "terraced": [3631,3177,null,3500,null,null,3901,3773,3770,null,3581,3866,4276,3809,4576,3768,3905]
      },
      "count": {
        "studio": [1,1,2,7,3,2,1,2,2,4,4,4,3,6,3,2,null],
        "two": [14,17,17,16,8,14,19,15,11,7,16,13,20,61,21,7,15],
        "three": [13,15,9,17,18,13,25,14,13,18,17,30,31,46,13,17,18],
        "terraced": [12,12,6,21,7,10,15,18,16,8,17,15,18,17,10,21,14]
      }
    },
    {
      "code": "00880",
      "name": "Keski-Herttoniemi - Roihupelto",
      "zone": 4,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,4,3],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,3,3],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,4,5],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      }
    },
    {
      "code": "00890",
      "name": "Östersundom",
      "zone": 4,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
      },
      "count": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "two": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "three": [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
        "terraced": [null,null,null,null,null,null,null,null,null,null,2,1,1,8,1,3,2]
      }
    },
    {
      "code": "00900",
      "name": "Puotinharju",
      "zone": 4,
      "price": {
        "studio": [2909,3323,3284,3631,3795,3912,4198,3944,4108,4059,4533,3951,4145,3867,3560,null,null],
        "two": [2278,2423,2501,2579,2877,2969,2929,2964,3086,3192,3170,3357,3183,3090,2954,3091,2315],
        "three": [2013,2103,2187,2202,2344,2360,2403,2577,2554,2549,2728,2681,2921,2788,2568,2423,2183],
        "terraced": [null,null,null,null,null,null,null,null,null,null,null,null,3552,null,2835,null,null]
      },
      "count": {
        "studio": [16,15,20,20,22,14,19,13,14,16,18,18,12,12,11,5,3],
        "two": [31,30,48,25,20,23,24,27,19,26,43,28,42,26,21,11,18],
        "three": [23,37,22,41,28,26,27,28,31,20,56,46,32,24,25,23,28],
        "terraced": [4,1,2,1,2,8,2,6,4,4,5,6,7,5,8,1,2]
      }
    },
    {
      "code": "00910",
      "name": "Puotila",
      "zone": 4,
      "price": {
        "studio": [2907,3328,3723,3827,3749,3908,4135,4073,4080,3857,4209,4349,4339,4636,3985,4061,3413],
        "two": [2364,2568,3004,3141,3040,3094,3053,3204,3310,3319,3344,3679,3863,3768,3527,3079,3154],
        "three": [2223,2511,2729,2695,2817,2919,2773,2888,2913,2885,3156,2955,3453,3578,3269,3206,3128],
        "terraced": [null,null,null,null,null,null,null,null,3730,3453,null,null,null,3884,null,null,null]
      },
      "count": {
        "studio": [37,26,43,30,30,29,28,34,24,26,23,21,54,32,24,20,18],
        "two": [69,74,81,90,54,53,55,59,63,60,51,46,104,70,48,42,43],
        "three": [49,42,50,57,32,49,47,43,47,37,50,60,68,40,46,41,34],
        "terraced": [1,5,1,5,6,1,2,3,7,7,4,3,5,7,6,4,4]
      }
    },
    {
      "code": "00920",
      "name": "Myllypuro",
      "zone": 4,
      "price": {
        "studio": [2401,2673,3183,null,3367,null,3773,null,null,null,4074,4303,3743,null,null,3742,2931],
        "two": [2046,2335,2420,2611,2738,2822,2644,2779,2938,2915,3059,3168,3335,3390,2856,2703,2651],
        "three": [1756,2035,2086,2172,2184,2238,2296,2343,2339,2533,2632,2695,2886,2907,2844,2591,2589],
        "terraced": [2650,2694,2900,2752,3085,2864,3023,3112,3281,3085,3222,3356,3691,3541,3618,3474,3325]
      },
      "count": {
        "studio": [15,10,7,5,13,5,11,2,5,3,6,8,7,7,5,8,9],
        "two": [56,53,58,42,44,59,41,43,58,30,62,51,52,49,30,32,46],
        "three": [67,57,68,72,46,52,53,57,52,67,53,54,82,74,48,62,66],
        "terraced": [26,21,20,18,22,21,32,37,29,35,47,66,60,46,25,41,47]
      }
    },
    {
      "code": "00930",
      "name": "Itäkeskus - Marjaniemi",
      "zone": 4,
      "price": {
        "studio": [null,3096,null,null,null,null,4514,null,null,null,3659,null,4216,null,null,null,2329],
        "two": [2365,2631,2683,2725,3046,3086,3705,3017,2849,3067,2949,2909,3119,2803,2767,2604,2332],
        "three": [2228,2745,2510,2518,2714,2725,3297,2623,2651,2776,2760,2538,3197,3234,2229,2398,2163],
        "terraced": [3244,3304,3383,3660,3795,3668,3067,3689,3509,3630,3719,3267,3564,3999,4196,4077,3516]
      },
      "count": {
        "studio": [4,8,6,7,3,6,20,7,6,5,11,6,10,5,6,7,7],
        "two": [24,18,18,13,17,15,37,15,27,24,13,23,26,17,15,12,9],
        "three": [18,13,26,14,9,20,21,21,26,22,24,21,23,13,19,18,14],
        "terraced": [27,25,22,18,14,17,25,14,30,27,26,29,36,30,24,23,26]
      }
    },
    {
      "code": "00940",
      "name": "Kontula - Vesala - Kivikko",
      "zone": 4,
      "price": {
        "studio": [2653,3072,3098,3166,3371,3395,3415,3350,3369,3518,3264,3457,3762,4429,3463,3125,3073],
        "two": [2155,2315,2408,2392,2445,2316,2389,2303,2301,2382,2511,2552,2730,2749,2495,2205,2152],
        "three": [1864,2052,2036,2018,2101,2001,1974,1963,2037,1901,2154,2160,2363,2399,2250,2062,2000],
        "terraced": [2455,2513,2575,2628,2568,2805,2675,2728,2817,2867,2833,2805,2897,3003,2495,2579,2510]
      },
      "count": {
        "studio": [19,36,27,23,16,18,25,16,11,20,18,21,13,22,12,19,11],
        "two": [93,81,92,89,90,86,112,97,112,114,96,115,120,116,67,71,75],
        "three": [99,101,98,145,111,109,121,114,119,119,129,145,121,120,69,71,96],
        "terraced": [48,45,58,47,28,34,40,52,41,48,36,55,52,55,27,32,37]
      }
    },
    {
      "code": "00950",
      "name": "Vartioharju",
      "zone": 3,
      "price": {
        "studio": [null,null,null,null,null,null,null,null,null,null,null,null,5132,4846,3787,null,null],
        "two": [2479,2853,2794,3166,2813,2995,3485,3103,3173,null,null,3383,3985,3772,3446,3327,3073],
        "three": [null,null,null,null,null,null,2995,null,3121,null,null,3490,3781,3744,null,3492,3037],
        "terraced": [3007,3196,3190,3370,3489,3444,3069,3103,3561,3498,3285,3368,3671,3680,3682,3489,3165]
      },
      "count": {
        "studio": [3,null,3,null,1,5,2,null,2,4,1,7,9,8,6,4,3],
        "two": [6,9,12,10,14,12,7,6,6,4,5,14,20,18,8,12,9],
        "three": [5,1,1,4,2,2,9,5,10,5,6,15,18,9,3,9,12],
        "terraced": [34,28,50,38,24,27,33,36,48,39,44,50,62,50,34,38,32]
      }
    },
    {
      "code": "00960",
      "name": "Pohjois-Vuosaari",
      "zone": 4,
      "price": {
        "studio": [2716,3229,3302,3851,3838,4290,4265,4192,3734,4053,3710,3926,4029,3650,3505,3006,2752],
        "two": [2219,2309,2393,2514,2689,2732,2797,2797,2905,2910,3027,3074,3096,2935,2812,2440,2243],
        "three": [1998,2286,2256,2332,2462,2410,2487,2768,2582,2610,2627,2810,2734,2729,2510,2559,2322],
        "terraced": [2578,2823,3022,3055,2875,2978,3010,2920,3065,2964,2838,3087,3197,3429,3045,3065,2833]
      },
      "count": {
        "studio": [9,14,9,8,14,13,26,15,17,19,15,45,17,17,9,10,11],
        "two": [38,53,51,52,71,69,78,79,82,74,93,75,71,81,39,48,47],
        "three": [10,17,18,28,32,26,29,30,38,36,46,43,44,33,21,23,20],
        "terraced": [23,17,30,26,18,7,23,17,21,21,21,19,23,19,14,7,14]
      }
    },
    {
      "code": "00970",
      "name": "Mellunmäki",
      "zone": 4,
      "price": {
        "studio": [2752,3003,3193,3432,3686,3621,3365,3585,3500,3200,3366,3543,3462,3528,3098,2647,2700],
        "two": [2324,2469,2485,2576,2589,2532,2474,2409,2560,2397,2480,2440,2645,2996,2483,2347,1949],
        "three": [2055,2198,2153,2236,2187,2186,2332,2155,2180,2065,2192,2030,2250,3004,2386,1983,1812],
        "terraced": [2493,null,null,2792,3086,2688,3237,3030,2912,null,2998,3058,3022,3460,3246,2953,2787]
      },
      "count": {
        "studio": [17,23,27,25,6,20,19,21,24,20,16,22,10,42,14,19,12],
        "two": [85,67,64,75,68,54,83,79,75,64,60,67,79,117,37,32,36],
        "three": [49,62,56,75,52,51,36,55,49,57,41,65,72,133,42,23,46],
        "terraced": [14,14,11,23,18,11,17,19,15,16,15,32,20,20,18,15,8]
      }
    },
    {
      "code": "00980",
      "name": "Etelä-Vuosaari",
      "zone": 4,
      "price": {
        "studio": [3163,3072,3235,3090,3418,3695,3245,3777,4009,4049,3826,4266,4179,3924,3890,3345,3244],
        "two": [2564,2685,2681,2725,3023,3158,3342,3218,3327,3242,3371,3459,3452,3411,3093,3058,2759],
        "three": [2317,2696,2664,2594,2741,2829,2705,2851,2837,2781,3183,3221,3300,3241,3142,2744,2707],
        "terraced": [2801,3051,3193,3280,3248,3288,3109,3276,3239,3315,3731,3355,3288,3380,3332,3456,3233]
      },
      "count": {
        "studio": [18,23,20,21,8,15,19,22,23,15,17,30,73,19,14,8,12],
        "two": [92,110,84,117,80,105,86,82,87,80,76,101,129,73,62,50,71],
        "three": [68,95,81,90,63,91,55,103,84,79,74,99,107,91,58,65,60],
        "terraced": [41,48,45,58,43,41,34,44,50,52,104,46,79,46,34,41,58]
      }
    },
    {
      "code": "00990",
      "name": "Aurinkolahti",
      "zone": 2,
      "price": {
        "studio": [3780,4103,4409,4667,4722,4566,4942,4971,5336,5100,5495,5488,6298,5775,5258,4943,null],
        "two": [3744,3931,3934,4270,4418,4394,4523,4577,4741,4907,4958,5128,5256,5252,4854,4589,4381],
        "three": [3580,3857,3975,4002,4160,4120,4230,4212,4454,4619,4687,4705,4952,4867,4661,4503,4494],
        "terraced": [3175,3441,3798,3674,3665,3678,3771,3688,3621,null,3511,4112,4392,4073,null,null,4345]
      },
      "count": {
        "studio": [16,15,15,24,13,11,10,15,9,17,12,19,13,14,10,11,7],
        "two": [118,71,86,89,66,60,66,60,81,79,71,113,77,69,42,23,48],
        "three": [68,93,65,78,67,73,61,53,83,63,67,96,81,92,53,51,55],
        "terraced": [11,10,12,12,11,9,12,7,8,2,9,8,7,7,2,5,6]
      }
    }
  ],
  "city": {
    "years": [2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025],
    "price": {
      "all": [3097,3259,3351,3345,3712,3930,4041,4198,4236,4290,4392,4596,4782,4959,5308,5646,5690,5278,5074,4983],
      "terraced": [2827,2979,2946,2921,3157,3241,3278,3374,3379,3352,3415,3424,3528,3573,3681,3882,4046,3840,3697,3672],
      "flats": [3141,3310,3420,3436,3831,4078,4205,4375,4420,4491,4602,4848,5052,5257,5608,5972,5993,5543,5328,5225]
    },
    "count": {
      "all": [13220,13212,11276,11914,12808,12953,12997,11008,10070,11360,11024,11138,10839,11853,12908,14219,12317,9000,9261,10455],
      "terraced": [1286,1334,1136,1264,1293,1296,1392,1105,1007,1215,1250,1280,1309,1312,1599,1765,1479,1046,1205,1243],
      "flats": [11911,11850,10114,10623,11496,11603,11570,9883,9047,10115,9741,9831,9501,10514,11308,12453,10835,7954,8056,9211]
    }
  },
  "index": {
    "years": [1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025],
    "series": {
      "helsinki": {
        "nominal": [77.9,94.9,88.1,71.8,55.9,53.8,59.7,56.5,58.9,71.9,80,89.2,100,99.5,109.7,116.8,123.8,131.6,144.5,154.2,154.8,155.8,174.2,181,185.5,192.8,193.8,194.4,199.8,206.6,214.8,221.5,232,246.2,244.9,225.4,214.9,210.6],
        "real": [105.9,121.1,105.9,83,62.9,59.3,65.1,61,63.3,76.2,83.6,92.2,100,97,105.3,111.2,117.6,123.9,133.7,139.2,134.3,135.4,149.6,150.2,149.7,153.3,152.6,153.3,157.1,161.2,165.8,169.2,176.7,183.5,170.4,147.6,138.6,135.4]
      },
      "zone1": {
        "nominal": [68.3,86.3,81.4,61.6,48.4,49,55.8,53.5,56.5,67.7,74.5,84.9,100,98.9,111.9,117,123.8,134.9,152.1,162.7,167,166,188.7,198.5,202.1,215,213.6,215.9,223.4,232.2,247.1,257.8,272.9,296.1,292.8,271.1,261.9,260.2],
        "real": [92.9,110.1,97.9,71.1,54.5,54,60.8,57.8,60.6,71.8,77.9,87.8,100,96.4,107.4,111.3,117.6,127,140.8,146.8,144.9,144.3,162,164.7,163,171,168.2,170.3,175.6,181.1,190.7,196.9,207.9,220.7,203.8,177.5,168.9,167.2]
      },
      "zone2": {
        "nominal": [78.5,95.1,87,71.9,56,53.8,60.2,56.9,59.5,72.4,80.5,89.3,100,99.9,110.1,117.1,124.4,131.6,144.7,155.2,156.1,158.2,177.5,186.5,191.9,200.6,204.7,207.3,214.7,222.8,234.2,243.4,258,271.2,269.4,245.8,235.1,228.2],
        "real": [106.7,121.3,104.5,83,63,59.3,65.6,61.4,63.9,76.7,84.1,92.3,100,97.4,105.7,111.4,118.1,123.9,133.9,140.1,135.4,137.5,152.4,154.7,154.8,159.5,161.1,163.5,168.7,173.8,180.8,185.9,196.5,202.2,187.5,161,151.6,146.7]
      },
      "zone3": {
        "nominal": [83.5,101.5,93.3,80.3,62.3,58.2,62.9,59.4,60.3,74.5,84.1,92.9,100,100.4,108.3,117.2,124.9,130.2,140.9,151.1,149,149.6,166.8,171,175.4,178.7,179.1,179.1,183.3,188.6,191.9,196.7,203.9,216.7,216.4,201.8,189.3,190.1],
        "real": [113.5,129.4,112.2,92.7,70.1,64.1,68.5,64.1,64.7,79,87.9,96,100,97.9,104,111.5,118.6,122.6,130.4,136.4,129.2,130.1,143.2,141.8,141.5,142.2,141,141.3,144.1,147.1,148.1,150.3,155.3,161.5,150.6,132.2,122.1,122.1]
      },
      "zone4": {
        "nominal": [87.4,102.9,97.5,81.9,62.7,57.9,61.8,57.5,60,74.8,83.8,92.6,100,98.4,106.5,115.6,121.6,128,138.3,145.3,144.9,145.7,159.8,162.7,166.1,169.8,168.8,166.1,168.5,173.2,176,177.9,181.9,191,191.7,176,165.3,157.7],
        "real": [118.8,131.2,117.1,94.5,70.5,63.8,67.4,62.1,64.4,79.3,87.6,95.7,100,95.9,102.3,110,115.5,120.5,128,131.2,125.7,126.7,137.2,134.9,134,135,132.9,131.1,132.5,135.1,135.9,135.9,138.6,142.4,133.4,115.3,106.6,101.4]
      },
      "capitalRegion": {
        "nominal": [79.9,97.5,90.8,74.6,57.9,54.5,60,57,59.1,72.5,81,90.2,100,99.6,109.2,116.1,123.6,130.7,141.6,151.4,152.1,152.1,169.4,175.1,179.2,183.6,183.9,183.7,187.6,192.5,197.7,202.4,209.6,221.2,220.4,203.2,194.4,189.9],
        "real": [108.6,124.4,109.1,86.2,65.1,60.1,65.4,61.6,63.5,76.9,84.7,93.3,100,97.1,104.8,110.5,117.4,123.1,131.1,136.7,132,132.3,145.5,145.2,144.5,146,144.8,144.9,147.5,150.2,152.6,154.6,159.7,164.9,153.4,133.1,125.3,122.1]
      },
      "finland": {
        "nominal": [80.5,98.7,94.7,81.6,66.5,60.9,64.6,62.4,64.6,76.5,84.5,92.9,100,99.5,106.8,113.6,121.9,129.3,139,146.6,147.5,147,159.9,164.2,166.9,169.6,168.6,167.2,168.7,170.4,172.1,173.3,175.8,182.4,183,171.2,165.1,160.6],
        "real": [109.5,125.9,113.8,94.2,74.9,67.1,70.5,67.4,69.3,81.1,88.4,96,100,97,102.5,108.1,115.8,121.8,128.6,132.4,127.9,127.8,137.3,136.2,134.7,134.8,132.7,131.9,132.6,132.9,132.9,132.4,133.9,136,127.3,112.1,106.5,103.2]
      }
    }
  },
  "latest": {
    "quarter": "2026Q2",
    "yearChangePct": -4.3,
    "realYearChangePct": -5.4,
    "pricePerM2": 4916,
    "count": 1986,
    "preliminary": true
  }
}
